apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-imagemagick-policy
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "common") | nindent 4 }}
  {{- with include "app.annotations.custom" (dict "context" . "component" "common") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  policy.xml: |
    {{- tpl (.Files.Get "files/common/imagemagick-policy.xml.tpl") (dict "imagemagickTimeoutSeconds" (.Values.pipeline.imagemagick_timeout_seconds | default 600)) | nindent 4 }}
