apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-secret
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.secret.pvc.accessModes | default "ReadWriteMany" | quote }}
  resources:
    requests:
      storage: {{ .Values.secret.pvc.storage | quote }}
