apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  labels:
    ingressclass: {{ .Values.ingress.className }}
  name: {{ include "app.fullname" . }}-mtls
spec:
  clientAuth:
    secretNames:
      - self-signed-mtls-cert
    clientAuthType: RequireAndVerifyClientCert