# Image version
ARG OPEN_WEBUI_IMAGE_VERSION="v0.6.15"

# We can not pull thus through CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX
# as this is not hosted on dockerhub
FROM ghcr.io/open-webui/open-webui:${OPEN_WEBUI_IMAGE_VERSION}
