# Image version
ARG OPEN_WEBUI_IMAGE_VERSION="v0.9.6-slim"

# We can not pull this through CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX
# as this is not hosted on dockerhub
FROM ghcr.io/open-webui/open-webui:${OPEN_WEBUI_IMAGE_VERSION}
