{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-api
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "api"
  annotations:
    {{- toYaml .Values.api.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.api.ingress.className }}
  rules:
    - host: api.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ include "app.fullname" . }}-external-vault-tls
      hosts:
        - api.{{ .Values.domain }}
  {{- end }}
{{- end }}
