apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-ollama
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  {{- if not .Values.ollama.hpa.enabled }}
  replicas: {{ .Values.ollama.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-ollama
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-ollama
    spec:
      initContainers:
        - name: copy-ollama-models
          image: &container-image {{ .Values.image.registry }}/{{ .Values.ollama.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.ollama.image.tag }}
          command:
            - /bin/sh
            - -c
            - |
              echo "Copying preloaded models to PVC..."
              cp \
                --recursive \
                --update \
                /root/.ollama/models/* /ollama-models/
          volumeMounts:
            - name: ollama-models
              mountPath: /ollama-models
      containers:
        - name: ollama
          image: *container-image
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ollama
              containerPort: {{ .Values.ollama.service.port }}
          env:
            - name: OLLAMA_MODELS
              value: /ollama-models
          {{- if .Values.ollama.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /api/ps
              port: {{ .Values.ollama.service.port }}
            initialDelaySeconds: {{ default 0 .Values.ollama.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 20 .Values.ollama.readinessProbe.periodSeconds }}
            failureThreshold: {{ default 3 .Values.ollama.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.ollama.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /api/ps
              port: {{ .Values.ollama.service.port }}
            initialDelaySeconds: {{ default 0 .Values.ollama.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 20 .Values.ollama.livenessProbe.periodSeconds }}
            failureThreshold: {{ default 6 .Values.ollama.livenessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: ollama-models
              mountPath: /ollama-models
          {{- if .Values.ollama.resources }}
          resources: {{- toYaml .Values.ollama.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: ollama-models
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-ollama-models