apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-ollama
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  ports:
    - port: {{ .Values.ollama.service.port }}
      name: ollama
      targetPort: {{ .Values.ollama.service.port }}
  selector:
    app: {{ include "app.name" . }}-ollama
