apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: loom

# Production configuration as default at top level
build:
  local:
    concurrency: 0
    useBuildkit: true
    tryImportMissing: true
  tagPolicy:
    customTemplate:
      template: "prod-{{.INPUT_DIGEST}}"
  artifacts:
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/api
      context: backend
      docker:
        dockerfile: api.Dockerfile
        target: production
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/api"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/worker
      context: backend
      docker:
        dockerfile: worker.Dockerfile
        target: production
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/worker"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/crawler
      context: backend
      docker:
        dockerfile: crawler.Dockerfile
        target: production
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/crawler"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/frontend
      context: Frontend
      docker:
        dockerfile: Dockerfile
        target: production
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/frontend"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/mongodb
      context: MongoDB
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/mongodb"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/elasticsearch
      context: ElasticSearch
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/elasticsearch"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/rabbit
      context: Rabbit
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/rabbit"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/redis
      context: Redis
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/redis"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/tika
      context: tika-server
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/tika"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/rspamd
      context: rspamd
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/rspamd"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/fluentd
      context: fluentd
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/fluentd"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/prometheus
      context: Prometheus
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/prometheus"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/grafana
      context: Grafana
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/grafana"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/ollama
      context: ollama
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/ollama"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/libretranslate
      context: libretranslate
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/libretranslate"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/open-webui
      context: open-webui
      docker:
        dockerfile: Dockerfile
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/open-webui"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/dovecot
      context: dovecot
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/dovecot"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/roundcube
      context: roundcube
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/roundcube"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/minio
      context: minio
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: '{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX "docker.io"}}'
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/minio"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/mc
      context: minio
      docker:
        dockerfile: mc.Dockerfile
        buildArgs:
          DOCKER_REGISTRY: '{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX "docker.io"}}'
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/mc"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/alpine
      context: alpine
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/alpine"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/elasticvue
      context: elasticvue
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/elasticvue"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/mongo-express
      context: MongoDB/mongo-express
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/mongo-express"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]
    - image: registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/redisinsight
      context: Redis/redisinsight
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: "{{or .CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX \"docker.io\"}}"
        cacheFrom:
          - "registry.gitlab.com/swiss-armed-forces/cyber-command/cea/loom/redisinsight"
      hooks:
        after:
          - command: ["./cicd/tag_latest.sh"]

# Production manifests configuration as default
manifests:
  helm:
    releases:
      - name: production
        namespace: loom
        chartPath: charts
        valuesFiles:
          - charts/values.yaml
          - charts/values-overwrites.yaml


# Minimal profiles - only overrides
profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      # Patch build configuration for dev
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "dev-{{.INPUT_DIGEST}}"
      # Patch api artifact for dev target and sync
      - op: replace
        path: /build/artifacts/0/docker/target
        value: dev
      - op: add
        path: /build/artifacts/0/sync
        value:
          manual:
            - src: "api/**"
              dest: /code
            - src: "common/**"
              dest: /code
      # Patch worker artifact for dev target and sync
      - op: replace
        path: /build/artifacts/1/docker/target
        value: dev
      - op: add
        path: /build/artifacts/1/sync
        value:
          manual:
            - src: "common/**"
              dest: /code
            - src: "worker/**"
              dest: /code
      # Patch crawler artifact for dev target and sync
      - op: replace
        path: /build/artifacts/2/docker/target
        value: dev
      - op: add
        path: /build/artifacts/2/sync
        value:
          manual:
            - src: "common/**"
              dest: /code
            - src: "crawler/**"
              dest: /code
      # Patch frontend artifact for dev target and sync
      - op: replace
        path: /build/artifacts/3/docker/target
        value: dev
      - op: add
        path: /build/artifacts/3/sync
        value:
          manual:
            - src: "**"
              dest: /code
      # Patch open-webui artifact for nodejs runtime
      - op: add
        path: /build/artifacts/15/runtimeType
        value: nodejs
      # Patch manifests for development
      - op: replace
        path: /manifests/helm/releases/0/name
        value: development
      - op: add
        path: /manifests/helm/releases/0/valuesFiles/-
        value: charts/values-development.yaml

  - name: prod
    activation:
      - command: prod
      # No patches needed - production is the default
