{{- if .Values.minio.podDisruptionBudget.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodDisruptionBudget" }}
apiVersion: policy/v1beta1
{{- else }}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: minio
  labels:
    app: {{ template "app.name" . }}
spec:
  maxUnavailable: {{ .Values.minio.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
{{- end }}
