{{- if eq .Values.minio.mode "standalone" }}
{{- if and .Values.minio.persistence.enabled (not .Values.minio.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.fullname" . }}-minio
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.minio.persistence.annotations }}
  annotations: {{- toYaml .Values.minio.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.minio.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size | quote }}
  {{- if .Values.minio.persistence.storageClass }}
  {{- if (eq "-" .Values.minio.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.minio.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  {{- if .Values.minio.persistence.volumeName }}
  volumeName: "{{ .Values.minio.persistence.volumeName }}"
  {{- end }}
{{- end }}
{{- end }}
