apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app.fullname" . }}-elasticsearch-pdb
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "elasticsearch") | nindent 4 }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-elasticsearch
