apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-elasticsearch
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  clusterIP: None  # Makes it headless
  publishNotReadyAddresses: true  # Critical for startup communication
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      name: elasticsearch
      targetPort: {{ .Values.elasticsearch.service.port }}
  selector:
    app: {{ include "app.name" . }}-elasticsearch