{{- if and .Values.prometheus.enabled .Values.prometheus.collectClusterMetrics  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.fullname" . }}-prometheus
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "prometheus") | nindent 4 }}
    app.kubernetes.io/component: monitoring
  {{- with include "app.annotations.custom" (dict "context" . "component" "prometheus") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/proxy
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
    - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
{{- end }}
