{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-prometheus
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
spec:
  ports:
    - port: {{ .Values.prometheus.service.port }}
      name: prometheus
      targetPort: {{ .Values.prometheus.service.port }}
  selector:
    app: {{ include "app.name" . }}-prometheus
{{- end }}
