{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-prometheus
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
spec:
  accessModes:
    - {{ .Values.prometheus.pvc.accessModes | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ .Values.prometheus.pvc.storage | quote }}
{{- end }}