{{- define "app.redis.configMap" -}}
{{- $component := .component -}}
{{- $values := index .Values $component -}}
{{- $memoryValue := default (dig "resources" "requests" "memory" "" $values) (dig "resources" "limits" "memory" "" $values) -}}
{{- $memoryLimitBytes := include "SI-to-bytes" $memoryValue | int64 -}}
{{- $memoryLimitThresholdPercent := dig "memoryLimitThresholdPercent" 0.6 $values -}}
{{- $memoryLimitBytes := mulf $memoryLimitBytes $memoryLimitThresholdPercent | int64 -}}
{{- $maxmemoryPolicy := dig "maxmemoryPolicy" "volatile-ttl" . -}}
{{- $stopWritesOnBgsaveError := dig "stopWritesOnBgsaveError" "no" . -}}
{{- $aofLoadTruncated := dig "aofLoadTruncated" "yes" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-{{ $component }}-config
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" $component) | nindent 4 }}
data:
  redis.conf: |
    {{- tpl (.Files.Get "files/redis/redis.conf.tpl") (dict "memoryLimitBytes" $memoryLimitBytes "maxmemoryPolicy" $maxmemoryPolicy "stopWritesOnBgsaveError" $stopWritesOnBgsaveError "aofLoadTruncated" $aofLoadTruncated) | nindent 4 }}
{{- end -}}
