{{- define "app.redis.statefulset" -}}
{{- $component := .component -}}
{{- $values := index .Values $component -}}
{{- $memoryValue := default (dig "resources" "requests" "memory" "" $values) (dig "resources" "limits" "memory" "" $values) -}}
{{- $redisMemoryLimitBytes := include "SI-to-bytes" $memoryValue | int64 -}}
{{- $pvcStorageMultiplier := dig "pvc" "storageMultiplier" 4 $values -}}
{{- $pvcStorageBytes := mulf $redisMemoryLimitBytes $pvcStorageMultiplier | int64 -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}-{{ $component }}
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" $component) | nindent 4 }}
    app.kubernetes.io/component: "{{ $component }}"
  {{- with include "app.annotations.custom" (dict "context" . "component" $component) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "app.fullname" . }}-{{ $component }}
  replicas: {{ $values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-{{ $component }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-{{ $component }}
        {{- include "app.labels.custom" (dict "context" . "component" $component) | nindent 8 }}
      {{- with include "app.annotations.custom" (dict "context" . "component" $component) }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $values.priorityClass }}
      priorityClassName: {{ include "app.fullname" $ }}-{{ . }}
      {{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: delete-redis-tmp-files
          image: {{ .Values.image.registry }}/{{ $values.initContainer.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) $values.initContainer.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - 'sh'
            - '-c'
            - |
              set -eux

              rm -rf  /data/temp-*.rdb
              rm -rf  /data/appendonlydir/temp-*
          volumeMounts:
            - mountPath: /data
              name: redis
          {{- if $values.initContainer.resources }}
          resources: {{- toYaml $values.initContainer.resources | nindent 12 }}
          {{- end }}
      containers:
        - name: {{ $component }}
          image: {{ .Values.image.registry }}/{{ $values.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) $values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ $component }}
              containerPort: {{ $values.service.port }}
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              readOnly: true
              subPath: redis.conf
            - mountPath: /data
              name: redis
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli ping
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 120
          {{- if $values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli ping
            initialDelaySeconds: {{ default 0 $values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 20 $values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ default 10 $values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ default 3 $values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if $values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli ping
            initialDelaySeconds: {{ default 0 $values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 20 $values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ default 10 $values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ default 6 $values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if $values.resources }}
          resources: {{- toYaml $values.resources | nindent 12 }}
          {{- end }}
        {{- if $values.exporter }}
        {{- if $values.exporter.enabled }}
        - name: redis-exporter
          image: {{ .Values.image.registry }}/{{ $values.exporter.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) $values.exporter.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_ADDR
              value: "redis://localhost:{{ $values.service.port }}"
          ports:
            - name: metrics
              containerPort: {{ $values.exporter.port }}
              protocol: TCP
          resources:
            {{- toYaml $values.exporter.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
        {{- end }}
        {{- end }}
      volumes:
        - name: redis-config
          configMap:
            name: {{ include "app.fullname" . }}-{{ $component }}-config
  volumeClaimTemplates:
    - metadata:
        name: redis
        {{- with include "app.pvc.labels.custom" (dict "context" . "component" $component) }}
        labels:
          {{- . | nindent 10 }}
        {{- end }}
        {{- with include "app.pvc.annotations.custom" (dict "context" . "component" $component) }}
        annotations:
          {{- . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ default "ReadWriteOnce" (dig "pvc" "accessModes" "" $values) | quote }}
        resources:
            requests:
              storage: {{ printf "%d" $pvcStorageBytes }}
        {{- if and $values.pvc $values.pvc.storageClass }}
        storageClassName: {{ $values.pvc.storageClass }}
        {{- end }}
{{- end -}}
