"""Point-and-click support for the Loom appliance's console session.

A Linux virtual console has no mouse driver behind it. `console_codes(4)` is
explicit that mouse reports reach a console's input stream "only when the
virtual terminal driver receives a mouse update ioctl", and that those ioctls
"must be generated by a mouse-aware user-mode application such as the gpm(8)
daemon" -- so something has to stand between the mouse and whatever is reading
the terminal. gpm is half of it: it decodes the device, tracks an absolute
position and draws the pointer. What gpm does *not* do -- verified in its
source, `src/daemon/do_selection.c`, which never passes anything but sel_mode 3
and `event->clicks` -- is generate that ioctl. So `set -g mouse on` plus a
running gpm produces a pointer and no events at all.

This package is the other half. It sits between /dev/tty1 and the tmux client
as a pty, turns gpm events into SGR mouse reports, and lets tmux do all the
routing it already knows how to do: focus a pane on click, translate to
pane-relative coordinates, re-encode in whatever protocol each pane asked for,
drag borders, scroll.

Being in the output path is not incidental, it is the reason for the shape.
The kernel draws gpm's pointer by complementing one cell and *caching what was
there* (`complement_pos`, drivers/tty/vt/vt.c), then writing that cache back
when the pointer moves. A pane that repaints under a stationary pointer -- btop
and k9s do so continuously -- therefore gets a stale character written over it
the next time the mouse moves. Only a process that also owns the writes can
bracket them: clear the pointer, write, put it back. See `pointer`.
"""
