{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-grafana
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "grafana") | nindent 4 }}
    app.kubernetes.io/component: monitoring
  {{- with include "app.annotations.custom" (dict "context" . "component" "grafana") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.grafana.service.port }}
      name: grafana
      targetPort: {{ .Values.grafana.service.port }}
  selector:
    app: {{ include "app.name" . }}-grafana
{{- end }}