{{- if .Values.crawler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-crawler
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: crawler
spec:
  replicas: {{ .Values.crawler.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-crawler
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-crawler
    spec:
      initContainers:
        - name: check-minio-ready
          image: {{ .Values.image.registry }}/{{ .Values.crawler.initContainer.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.crawler.initContainer.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - 'sh'
            - '-c'
            - |
              set -eu

              until nc -vz {{ include "app.fullname" . }}-minio {{ .Values.minio.service.port }}; do
                echo "Waiting for minio service";
                sleep 1;
              done;
          {{- if .Values.crawler.initContainer.resources }}
          resources: {{- toYaml .Values.crawler.initContainer.resources | nindent 12 }}
          {{- end }}
      containers:
        - name: crawler
          image: {{ .Values.image.registry }}/{{ .Values.crawler.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.crawler.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Note: we do assume here that the MinIO-Intake-Key is at position 0
            {{- with index .Values.minio.svcaccts 0 }}
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .existingSecret }}"
                  key: secretkey
            - name: MINIO_ACCESS_KEY
              value: "{{ .accessKey }}"
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-settings
          volumeMounts:
          {{- if .Values.crawler.resources }}
          resources: {{- toYaml .Values.crawler.resources | nindent 12 }}
          {{- end }}
{{- end }}
