{{- if .Values.crawler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-crawler
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "crawler") | nindent 4 }}
    app.kubernetes.io/component: crawler
spec:
  replicas: {{ .Values.crawler.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-crawler
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-crawler
        {{- include "app.labels.custom" (dict "context" . "component" "crawler") | nindent 8 }}
    spec:
      initContainers:
        - name: check-seaweedfs-ready
          image: {{ .Values.image.registry }}/{{ .Values.crawler.initContainer.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.crawler.initContainer.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - 'sh'
            - '-c'
            - |
              set -eu

              until nc -vz {{ include "app.fullname" . }}-seaweedfs-filer {{ .Values.seaweedfs.s3.port }}; do
                echo "Waiting for SeaweedFS S3 service";
                sleep 1;
              done;
          {{- if .Values.crawler.initContainer.resources }}
          resources: {{- toYaml .Values.crawler.initContainer.resources | nindent 12 }}
          {{- end }}
      containers:
        - name: crawler
          image: {{ .Values.image.registry }}/{{ .Values.crawler.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.crawler.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-settings
          {{- if .Values.crawler.resources }}
          resources: {{- toYaml .Values.crawler.resources | nindent 12 }}
          {{- end }}
{{- end }}
