{{- if .Values.crawler.enabled }}
{{- include "app.crawler.deployment" (dict
  "Values"       .Values
  "Chart"        .Chart
  "Release"      .Release
  "nameSuffix"   ""
  "s3Storage"    nil
  "bucketAlias"  nil
  "sourceId"     nil
  "replicaCount" .Values.crawler.replicaCount
  "resources"    .Values.crawler.resources
) }}
{{- end }}
