{{- if .Values.crawler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-crawler
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: crawler
spec:
  replicas: {{ .Values.crawler.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-crawler
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-crawler
    spec:
      containers:
        - name: api
          image: {{ .Values.image.registry }}/{{ .Values.crawler.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.crawler.image.tag }}
          env:
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: loom-minio-secret
                  key: secretkey
            - name: MINIO_ACCESS_KEY
              {{ with index .Values.minio.svcaccts 0}}
              value: {{.accessKey | quote}}
              {{end}}
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-settings
          volumeMounts:
          {{- if .Values.crawler.resources }}
          resources: {{- toYaml .Values.crawler.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: secret
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-secret
{{- end }}
