{{- if .Values.dovecot.ingress.imap.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "app.fullname" . }}-dovecot-imap
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dovecot
spec:
  entryPoints:
    - imap
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "app.fullname" . }}-dovecot
          port: {{ .Values.dovecot.service.port.imap }}
{{- end }}