{{- if .Values.dovecot.ingress.imaps.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "app.fullname" . }}-dovecot-imaps
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    ingressclass: {{ .Values.dovecot.ingress.imaps.className }}
    app.kubernetes.io/component: dovecot
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`dovecot.{{ .Values.domain }}`)
      services:
        - name: {{ include "app.fullname" . }}-dovecot
          port: {{ .Values.dovecot.service.port.imap }}
  {{- if .Values.dovecot.ingress.imaps.tls.enabled }}
  tls:
    secretName: {{ include "app.fullname" . }}-certificate
    domains:
      - main: dovecot.{{ .Values.domain }}
    {{- if .Values.certificate.requireClientCert }}
    options:
      name: {{ include "app.fullname" . }}-mtls
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{- if .Values.dovecot.ingress.imap.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "app.fullname" . }}-dovecot-imap
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    ingressclass: {{ .Values.dovecot.ingress.imap.className }}
    app.kubernetes.io/component: dovecot
spec:
  entryPoints:
    - imap
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "app.fullname" . }}-dovecot
          port: {{ .Values.dovecot.service.port.imap }}
{{- end }}