#!/usr/bin/env bash
# Builds, and optionally flashes, a Loom appliance USB installer image.
set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CONTEXT_DIR=$(git -C "${SCRIPT_DIR}" rev-parse --show-toplevel)

# nixpkgs comes from devenv's `inputs.nixpkgs-stable`, passed as --nixpkgs by
# the build-appliance-image devenv script. That keeps devenv.lock the single
# nixpkgs pin in this repository. No default: there is nothing sensible to fall
# back to, and validate_environment says so rather than letting nix fail later.
NIXPKGS=""

# nixos-hardware, by the same route and for the same reason. It carries the
# upstream profile for the x86 platforms -- see nixos/platforms/<id>.nix -- and
# is deliberately not optional: a stick built without it would differ silently
# from every other stick, which is the failure this directory is built to avoid.
NIXOS_HARDWARE=""

OUTPUT_DIR="${CONTEXT_DIR}/.appliance-build"

# Which box this stick is for. The nix system follows from it unless --system
# says otherwise; see nixos/platforms/ for what else each one carries.
PLATFORM="spark"
KNOWN_PLATFORMS=(spark evo-x2 nuc12)
NIX_SYSTEM=""
# The chosen platform's GPU vendor, resolved once in Main below rather than at
# each use: calling platform_gpu inside a condition would disable `set -e` in
# it, the same trap --platform avoids by matching against KNOWN_PLATFORMS.
PLATFORM_GPU=""
MINIKUBE_IP="192.168.49.2"

# Empty means "let the platform's netMatch pick the interface, and rename it to
# loom0". Only set by --interface, to override that match with a literal name.
LOOM_INTERFACE=""

# The optional access point (nixos/wifi.nix). Off by default: an appliance is
# an island reached over a cable, and --wifi is an explicit decision to extend
# it to everyone in radio range. SSID and passphrase are generated below unless
# given, and are printed by `report` -- they are baked into the closure, so they
# are also world-readable in /nix/store and present on the stick.
ENABLE_WIFI=false
WIFI_SSID=""
WIFI_PSK=""
# Empty keeps the radio on 2.4GHz under regulatory domain 00. Setting a country
# code moves it to 5GHz, which domain 00 forbids an AP from beaconing on at all.
WIFI_COUNTRY=""
# As LOOM_INTERFACE, but for the radio.
WIFI_INTERFACE=""

# 4096 bytes of /dev/urandom, matching boot.initrd.luks.devices.keyFileSize.
KEY_BYTES=4096
KEY_PARTLABEL="loom-key"
# How long flash_image waits for that partition to become visible before giving
# up. Generous, because the cost of being impatient is a stick with no key on
# it and the cost of waiting is a few seconds on the one run where it is slow.
KEY_PARTITION_TIMEOUT=30

# Put those 4096 bytes inside a LUKS2 container on the stick rather than writing
# them raw, with a generated word passphrase over it (nixos/key-store.nix). Off
# by default, because it costs unattended boot: the box stops at a prompt in
# stage 1 and does not come back on its own after a power cut.
#
# What it buys is that the stick stops being a bearer token. Unlocked, holding it
# is enough; locked, it is one factor of two. See Documentation/appliance.md.
LOCK_KEY=false
# Seven EFF words is ~90 bits, which is more than argon2id needs to be out of
# reach and still short enough to read off a printout and type at a console.
#
# The default is a constant of its own because `resolve_lock_key` compares
# against it to tell "not given" from "given", the way the wifi flags use "" --
# a count has no empty value to use instead.
LOCK_KEY_WORDS_DEFAULT=7
LOCK_KEY_WORDS="${LOCK_KEY_WORDS_DEFAULT}"
# Below this the passphrase stops being the strong half of the pair, and the
# whole flag becomes theatre.
LOCK_KEY_MIN_WORDS=6
LOCK_KEY_OUT=""
# What the container is opened as while it is being written, here on the build
# host. Deliberately NOT nixos/key-store.nix's `mapping`, which is the name the
# appliance opens it under: the two never coexist, and a distinct name means
# flashing a stick on a machine that is itself running a Loom appliance -- or
# flashing two sticks at once -- cannot collide with an open mapping.
KEYSTORE_MAPPING="loom-keystore-flash"
# Generated by generate_luks_key when LOCK_KEY is true, printed by `report`, and
# never written anywhere but --lock-key-out. Unlike the WiFi PSK next door it
# never reaches Nix and never reaches the stick.
KEY_PASSPHRASE=""

TAG=""
SUBNET=""
FLASH_DEVICE=""
KEY_BACKUP=""
# Build the CPU-only image for a platform that offloads to a GPU. Set by
# --no-gpu; see the flag's own comment for when that is the right answer.
DISABLE_GPU=false
# Add a getty on ttyS0 to both the installer and the box it installs. Set by
# --vm-serial, which exists for cicd/run_appliance_vm.sh and is refused
# alongside --flash: an image built with this is for a VM, not for a stick.
VM_SERIAL=false

# Run an SSH server on the installed box, keyed to a keypair generated below.
# Off by default and loudly announced when on: this is the one flag that takes
# back "there is no remote access", which Documentation/appliance.md states as a
# threat-model guarantee. See nixos/debug.nix.
DEBUG_ACCESS=false
# Where resolve_debug_key leaves the private half. Deliberately NOT cleaned up
# by atexit -- see the comment there -- because it is the whole output of the
# flag as far as the operator is concerned.
DEBUG_KEY_DIR=""

# The appliance's operator account. Must agree with `loomUser` in
# nixos/default.nix, which is what decides the account that actually exists;
# this is only what the generated ssh_config tells a client to ask for.
LOOM_USER="loom"

# Which out-link build_image writes and image_file then reads. A debug build
# gets its own name so two images in one output directory cannot be confused,
# and so `--out-link` never overwrites the other kind's symlink. Resolved in
# Main, once --debug has been parsed.
IMAGE_LINK=""

ASSUME_YES=false
ALLOW_CROSS=false
VERBOSE=false
SKIP=()

WORK_DIR=""
KEY_DIR=""

# variables defined in vars.sh, here for shellcheck:
LOOM_HOSTS_FQDN=()
NAMESPACE=""
LOOM_CHAT_MODEL=""

STEPS=(
    validate_environment
    fetch_tags
    resolve_tag
    resolve_subnet
    resolve_wifi
    resolve_lock_key
    resolve_debug_key
    prepare_workdir
    prepare_repo
    verify_repo
    normalize_git_config
    generate_loom_hosts
    build_image
    report
)

# Appended in Main when --flash is given.
FLASH_STEPS=(
    confirm_flash
    generate_luks_key
    flash_image
    write_key_partition
    verify_flash
    backup_luks_key
    backup_key_passphrase
)

#
# Helpers
#

check_command(){
    if ! command -v "${1}" > /dev/null; then
        echo >&2 "[!] Error: required command not found: ${1}"
        exit 1
    fi
}

# The architecture each platform is. Must agree with `nixSystem` in the matching
# nixos/platforms/<id>.nix -- nixos/default.nix asserts that they do, so a drift
# here fails during evaluation rather than on the box.
platform_system(){
    case "${1}" in
        spark)  printf 'aarch64-linux' ;;
        evo-x2) printf 'x86_64-linux'  ;;
        nuc12)  printf 'x86_64-linux'  ;;
        *)      return 1               ;;
    esac
}

# The GPU vendor each platform offloads Ollama to, empty for the CPU-only ones.
# Mirrors `gpuVendor` in the matching nixos/platforms/<id>.nix, which is the
# authority -- this copy exists so that --no-gpu can reject a platform with
# nothing to disable, and so the report below can say what the stick will do
# without evaluating the closure to find out.
platform_gpu(){
    case "${1}" in
        spark)  printf 'nvidia' ;;
        evo-x2) printf 'amd'    ;;
        nuc12)  printf ''       ;;
        *)      return 1        ;;
    esac
}

# What the `gpu` line of the report says. Three outcomes rather than a boolean,
# because "this box has none" and "this box has one and you turned it off" are
# different things to read back off a stick you are about to hand to someone.
gpu_report(){
    if [[ -z "${PLATFORM_GPU}" ]]; then
        printf 'none (CPU-only platform)'
    elif [[ "${DISABLE_GPU}" = true ]]; then
        printf 'disabled by --no-gpu (%s available)' "${PLATFORM_GPU}"
    else
        printf '%s' "${PLATFORM_GPU}"
    fi
}

#
# Steps
#

validate_environment(){
    local command host_arch free_gb

    # `partx` and `blockdev` rather than `partprobe`: see flash_image for why
    # parted is the wrong tool for re-reading an image-sized GPT on a larger
    # stick. Both are util-linux, which `lsblk` already requires.
    for command in git git-lfs nix-build jq lsblk sgdisk dd sync udevadm partx blockdev sudo head cmp install file; do
        check_command "${command}"
    done

    # Only under --lock-key, so an ordinary build does not acquire two
    # dependencies for a flag it is not using.
    if [[ "${LOCK_KEY}" = true ]]; then
        check_command cryptsetup
        check_command diceware
    fi

    if [[ -z "${NIXPKGS}" ]]; then
        echo >&2 "[!] Error: no nixpkgs given."
        echo >&2 "    Run this through devenv: 'build-appliance-image' passes --nixpkgs for you."
        echo >&2 "    To drive the script directly, pass --nixpkgs PATH yourself."
        exit 1
    fi
    if [[ ! -e "${NIXPKGS}/nixos/lib/eval-config.nix" ]]; then
        echo >&2 "[!] Error: '${NIXPKGS}' does not look like a nixpkgs checkout."
        exit 1
    fi

    if [[ -z "${NIXOS_HARDWARE}" ]]; then
        echo >&2 "[!] Error: no nixos-hardware given."
        echo >&2 "    Run this through devenv: 'build-appliance-image' passes --nixos-hardware for you."
        echo >&2 "    To drive the script directly, pass --nixos-hardware PATH yourself."
        exit 1
    fi
    if [[ ! -e "${NIXOS_HARDWARE}/common/pc/ssd/default.nix" ]]; then
        echo >&2 "[!] Error: '${NIXOS_HARDWARE}' does not look like a nixos-hardware checkout."
        exit 1
    fi

    # Cross-building a NixOS closure through emulation is slow, and needs a
    # binfmt handler that most hosts do not have, so refuse by default rather
    # than appear to hang or die halfway with a confusing message.
    host_arch="$(uname -m)"
    if [[ "${ALLOW_CROSS}" != true && "${NIX_SYSTEM}" == "${host_arch}-linux" ]]; then
        : # building natively
    elif [[ "${ALLOW_CROSS}" != true ]]; then
        echo >&2 "[!] Error: platform '${PLATFORM}' is ${NIX_SYSTEM}, but this host is ${host_arch}."
        echo >&2 "    Build it on a ${NIX_SYSTEM} host, or pass --allow-cross."
        echo >&2 "    Cross-building also needs an emulator for ${NIX_SYSTEM} on this host"
        echo >&2 "    (on NixOS: boot.binfmt.emulatedSystems = [ \"${NIX_SYSTEM}\" ];)."
        exit 1
    fi

    # git-lfs payloads must already be local: the appliance build has no network
    # budget for fetching them, and up.sh:412 fails without them on the box.
    local lfs_dir
    lfs_dir="$(git -C "${CONTEXT_DIR}" rev-parse --path-format=absolute --git-common-dir)/lfs/objects"
    if [[ ! -d "${lfs_dir}" ]]; then
        echo >&2 "[!] Error: no git-lfs objects in this checkout."
        echo >&2 "    Run: git lfs fetch --all"
        exit 1
    fi

    install --directory "${OUTPUT_DIR}"

    # Check the Nix store, not the output directory: the build happens in the
    # store, and the two are routinely on different filesystems -- a big /home
    # is no help when /nix is on a small root volume.
    local store_dir="${NIX_STORE_DIR:-/nix/store}"
    if [[ ! -d "${store_dir}" ]]; then
        echo >&2 "[!] Error: no Nix store at ${store_dir}."
        exit 1
    fi
    free_gb="$(df --output=avail --block-size=1G "${store_dir}" | tail --lines=1 | tr --delete ' ')"
    if [[ "${free_gb}" -lt 20 ]]; then
        echo >&2 "[!] Error: only ${free_gb} GB free on the filesystem holding ${store_dir};"
        echo >&2 "    the image build needs about 20 GB there."
        exit 1
    fi

    free_gb="$(df --output=avail --block-size=1G "${OUTPUT_DIR}" | tail --lines=1 | tr --delete ' ')"
    if [[ "${free_gb}" -lt 5 ]]; then
        echo >&2 "[!] Error: only ${free_gb} GB free at ${OUTPUT_DIR}; the image needs about 5 GB."
        exit 1
    fi
}

# Refresh the tag list the step below picks from. Without this the default is
# only as fresh as whenever this checkout was last fetched, and a stale pick is
# an expensive mistake to make quietly: an hour of build, and a stick that is
# indistinguishable from the right one until somebody boots it and reads the
# version off the console.
#
# Best-effort by design. A build host with no route to origin is a case this
# script supports -- the tags it already has are real, and the image is built
# from a local clone either way -- so an unreachable remote warns and carries
# on. Pass --skip-fetch_tags to keep it from trying at all.
fetch_tags(){
    if [[ -n "${TAG}" ]]; then
        # --tag already says which release this stick is. Fetching could not
        # change that answer, only slow it down.
        return
    fi

    if ! git -C "${CONTEXT_DIR}" remote get-url origin > /dev/null 2>&1; then
        echo "[*] No 'origin' remote; using the tags in this checkout."
        return
    fi

    echo "[*] Fetching tags from origin"
    # No --prune-tags and no --force: a tag that moved or vanished upstream is
    # not something to act on silently while preparing a release artefact.
    if ! git -C "${CONTEXT_DIR}" fetch --tags --quiet origin; then
        echo "[!] Could not reach origin. Falling back to the tags already in this"
        echo "[!] checkout, which may be older than the newest release."
    fi
}

resolve_tag(){
    local answer

    if [[ -n "${TAG}" ]]; then
        if ! git -C "${CONTEXT_DIR}" rev-parse --verify --quiet "refs/tags/${TAG}" > /dev/null; then
            echo >&2 "[!] Error: no such tag: ${TAG}"
            echo >&2 "    prepare_repo clones this checkout, so the tag has to exist here and"
            echo >&2 "    not only on the remote. Run: git -C '${CONTEXT_DIR}' fetch --tags"
            exit 1
        fi
        return
    fi

    # Two things about this listing:
    #
    #   * It is NOT `git describe`, which returns the nearest *ancestor* tag and
    #     so happily picks an ancient release when main has moved on.
    #   * versionsort.suffix is what stops 1.3.0-rc9 from outranking 1.3.0.
    #     Git's version sort otherwise places a longer string above the prefix
    #     it extends, so every release would be shadowed by its own last release
    #     candidate and this default would never pick a finished release at all.
    #     The repository's tags are exactly `X.Y.Z` and `X.Y.Z-rcN`, so one
    #     suffix covers it.
    TAG="$(git -C "${CONTEXT_DIR}" -c versionsort.suffix=-rc tag --list --sort=-v:refname | head --lines=1)"
    if [[ -z "${TAG}" ]]; then
        echo >&2 "[!] Error: this repository has no tags."
        echo >&2 "    The appliance runs Loom in offline mode, which requires a tagged checkout (up.sh:236)."
        exit 1
    fi

    echo "[*] Newest tag: ${TAG}"
    if [[ "${ASSUME_YES}" != true ]]; then
        read -r -p "[?] Build the appliance from ${TAG}? [y/N] " answer
        if [[ "${answer}" != "y" && "${answer}" != "Y" ]]; then
            echo >&2 "[!] Aborted. Pass --tag to choose a different one."
            exit 1
        fi
    fi
}

resolve_subnet(){
    local a b

    if [[ -n "${SUBNET}" ]]; then
        return
    fi

    # Randomised so two boxes on one wire cannot collide, and so a visitor's own
    # 10.0.0.0/24 or 192.168.1.0/24 does not either. 0 and 255 are avoided in
    # both octets to keep the range unremarkable.
    a="$(( (RANDOM % 254) + 1 ))"
    b="$(( (RANDOM % 254) + 1 ))"
    SUBNET="10.${a}.${b}"
}

# The access point's identity, fixed at build time and baked into the closure.
#
# Generated here rather than on the box so that `report` can tell the operator
# the SSID and passphrase before the stick has ever been booted. The cost is
# stated in the header: two boxes installed from one stick share a network.
resolve_wifi(){
    if [[ "${ENABLE_WIFI}" != true ]]; then
        # Guard against a flag that silently does nothing, which on a feature
        # this security-relevant is worse than an error.
        if [[ -n "${WIFI_SSID}${WIFI_PSK}${WIFI_COUNTRY}${WIFI_INTERFACE}" ]]; then
            echo >&2 "[!] Error: --wifi-* given without --wifi. Nothing would enable the access point."
            exit 1
        fi
        return
    fi

    if [[ -z "${WIFI_SSID}" ]]; then
        # A random suffix, not a bare "loom": two appliances within range of each
        # other must not advertise the same name, and an operator reading a QR
        # code off a monitor should be able to tell which box answered.
        WIFI_SSID="loom-$(random_token 4)"
    fi

    if [[ -z "${WIFI_PSK}" ]]; then
        # Four groups of five, like the LUKS recovery passphrase -- 23 characters
        # over a 32-symbol alphabet, comfortably past WPA's 8-character floor and
        # still transcribable by someone who cannot scan the QR code.
        WIFI_PSK="$(random_token 20 | sed --regexp-extended 's/(.{5})/\1-/g; s/-$//')"
    fi

    # nixos/wifi.nix asserts the same alphabet, and for the reason given there:
    # anything outside it needs a backslash escape inside the `WIFI:` URI on the
    # login screen, and agetty eats backslashes out of an issue file. Checked
    # here too so a hand-passed value fails in the second it takes to read the
    # flag rather than partway into a Nix evaluation.
    local value
    for value in "${WIFI_SSID}" "${WIFI_PSK}"; do
        if [[ ! "${value}" =~ ^[A-Za-z0-9_-]+$ ]]; then
            echo >&2 "[!] Error: '${value}' contains characters that cannot go on the console QR code."
            echo >&2 "[!] --wifi-ssid and --wifi-psk accept letters, digits, '-' and '_' only."
            exit 1
        fi
    done

    if (( ${#WIFI_PSK} < 8 )); then
        echo >&2 "[!] Error: --wifi-psk must be at least 8 characters (WPA minimum)."
        exit 1
    fi
}

# Everything about --lock-key that can be wrong before anything is built.
#
# The passphrase itself is not generated here but in `generate_luks_key`, which
# is a flash step: an image built without --flash has no key to put behind a
# passphrase, so generating one would only print a secret for a stick that does
# not exist.
resolve_lock_key(){
    if [[ "${LOCK_KEY}" != true ]]; then
        # As resolve_wifi: a sub-flag that silently does nothing is worse than an
        # error on a feature whose whole purpose is a security property.
        if [[ -n "${LOCK_KEY_OUT}" ]] \
            || [[ "${LOCK_KEY_WORDS}" != "${LOCK_KEY_WORDS_DEFAULT}" ]]; then
            echo >&2 "[!] Error: --lock-key-* given without --lock-key. The key would be written raw."
            exit 1
        fi
        return
    fi

    if [[ ! "${LOCK_KEY_WORDS}" =~ ^[0-9]+$ ]] || (( LOCK_KEY_WORDS < LOCK_KEY_MIN_WORDS )); then
        echo >&2 "[!] Error: --lock-key-words must be a number and at least ${LOCK_KEY_MIN_WORDS}."
        echo >&2 "[!] Fewer words than that stops being the strong half of the pair."
        exit 1
    fi

    if [[ -n "${LOCK_KEY_OUT}" ]]; then
        assert_secret_path "${LOCK_KEY_OUT}" "--lock-key-out"

        # The two factors must not end up in one file. Somebody who finds that
        # file has the stick's key *and* the passphrase over it, which is
        # precisely the position --lock-key exists to deny them.
        if [[ -n "${KEY_BACKUP}" ]]; then
            local phrase_path backup_path
            phrase_path="$(readlink --canonicalize "${LOCK_KEY_OUT}")"
            backup_path="$(readlink --canonicalize "${KEY_BACKUP}")"
            if [[ "${phrase_path}" = "${backup_path}" ]]; then
                echo >&2 "[!] Error: --lock-key-out and --key-backup must not be the same file."
                echo >&2 "[!] That file would hold both factors, which is no better than neither."
                exit 1
            fi
        fi
    fi

    # A warning rather than an error, because it is the same shape as the
    # existing behaviour: an image built without --flash has no key either way.
    # What is different is that this one cannot be keyed afterwards by hand.
    if [[ -z "${FLASH_DEVICE}" ]]; then
        echo "[!] --lock-key without --flash. The image will expect a locked key"
        echo "[!] partition, and only 'build-appliance-image --flash --lock-key'"
        echo "[!] writes one -- 'appliance-vm installer' cannot."
    fi
}

# Refuse a path that a secret must not be written to.
#
# Only the repository, and only because `git add -A` is one keystroke: there is
# no attempt here to judge where an operator keeps their secrets, which is not
# this script's business.
assert_secret_path(){
    local path="${1}" flag="${2}" resolved
    resolved="$(readlink --canonicalize "${path}")"
    if [[ "${resolved}" == "${CONTEXT_DIR}"/* ]]; then
        echo >&2 "[!] Error: refusing to write ${flag} inside the repository."
        exit 1
    fi
}

# N characters from the same alphabet install.sh uses for the recovery
# passphrase: unambiguous on a monitor (no l/1/0/O) and free of every character
# the `WIFI:` URI reserves.
random_token(){
    local want="${1}" raw=''
    # `head` bounds the read rather than cutting a `tr` that reads /dev/urandom
    # endlessly -- see install.sh `generate_passphrase` for why that matters.
    while (( ${#raw} < want )); do
        raw+="$(head --bytes=256 /dev/urandom |
            tr --delete --complement 'abcdefghijkmnpqrstuvwxyz23456789')"
    done
    printf '%s' "${raw:0:want}"
}

# The one key the debug image accepts, generated fresh for this image.
#
# Fresh rather than the build host's own ~/.ssh: an appliance key is a
# throwaway, it should die with the image, and reusing a personal key would put
# it in an authorized_keys file on a box that gets wiped and re-flashed by
# people who never chose to trust it.
#
# Only the public half reaches Nix. The private half stays here, outside the
# store and outside the repository, and the directory is deliberately left
# behind when this script exits -- it is the output of the flag.
#
# The ssh_config files matter more than they look: resolve_subnet randomises the
# /24 per image, so nothing downstream can hardcode the box's address. With
# them, reaching the box is `ssh -F <dir>/ssh_config loom-appliance` and needs
# no other knowledge -- which is the point, because the thing at the other end
# of that command is as often an agent as a person.
resolve_debug_key(){
    if [[ "${DEBUG_ACCESS}" != true ]]; then
        return
    fi

    check_command ssh-keygen

    # Named for the image it belongs to, so a bench with three of these lying
    # around says which stick each one opens. $TMPDIR rather than /run/user:
    # unlike the LUKS key this is meant to outlive the run, and a tmpfs under
    # /run/user is cleared when the session ends.
    DEBUG_KEY_DIR="$(mktemp --directory "${TMPDIR:-/tmp}/loom-appliance-debug-${TAG}-${PLATFORM}.XXXXXX")"
    chmod 0700 "${DEBUG_KEY_DIR}"

    # ed25519: small enough to read off a screen if it ever comes to that, and
    # the one algorithm every OpenSSH still in service accepts by default.
    # -N '' because an agent cannot type a passphrase, which is the whole use
    # case -- the key's protection is the 0700 directory and its short life.
    ssh-keygen -t ed25519 -N '' -q \
        -C "loom-appliance-debug ${TAG} ${PLATFORM}" \
        -f "${DEBUG_KEY_DIR}/id_ed25519"

    # Created empty rather than left to ssh, so the file exists with the right
    # mode before the first connection writes the box's host key into it.
    : > "${DEBUG_KEY_DIR}/known_hosts"
    chmod 0600 "${DEBUG_KEY_DIR}/known_hosts"

    # Two configs, because the same image is as likely to be booted in a VM as
    # written to a stick. See write_debug_ssh_config for what is in them.
    write_debug_ssh_config "${DEBUG_KEY_DIR}/ssh_config" "${SUBNET}.1" 22 \
        "The box on its own network -- plug a laptop into the appliance port and take a DHCP lease."
    write_debug_ssh_config "${DEBUG_KEY_DIR}/ssh_config.vm" localhost 2222 \
        "The same image under 'appliance-vm box --debug', which forwards 2222 to the guest's 22."
}

# One ready-to-use ssh_config, so that reaching the box needs no knowledge the
# build did not already have.
#
# `accept-new` rather than a baked host key. It is already non-interactive,
# which is what an agent needs, and it keeps a second secret out of /nix/store:
# a host private key passed through Nix would be world-readable on the stick,
# and the WiFi passphrase is quite enough of that.
#
# `IdentitiesOnly` because a developer's ssh-agent will otherwise offer its own
# keys first and the box -- which knows exactly one -- refuses the lot until
# MaxAuthTries runs out, which reads as "the key did not work".
write_debug_ssh_config(){
    local file="${1}" host="${2}" port="${3}" note="${4}"

    cat > "${file}" <<EOF
# Generated by cicd/build_appliance_image.sh for the ${TAG} ${PLATFORM} debug image.
# ${note}
#
# Use it with:  ssh -F ${file} loom-appliance
# Delete this whole directory when you are done with the box.
Host loom-appliance
    HostName ${host}
    Port ${port}
    User ${LOOM_USER}
    IdentityFile ${DEBUG_KEY_DIR}/id_ed25519
    IdentitiesOnly yes
    UserKnownHostsFile ${DEBUG_KEY_DIR}/known_hosts
    StrictHostKeyChecking accept-new
EOF
    chmod 0600 "${file}"
}

prepare_workdir(){
    local uid
    uid="$(id -u)"
    WORK_DIR="$(mktemp --directory)"
    # The LUKS key must never touch a disk. /run/user is a tmpfs.
    KEY_DIR="$(mktemp --directory --tmpdir="/run/user/${uid}")"
    chmod 0700 "${KEY_DIR}"
}

# Prepared with real git rather than a Nix fetcher, because up.sh's offline mode
# runs `git describe --exact-match --tags HEAD` (up.sh:236) inside the embedded
# checkout, and every Nix fetcher either drops `.git` or leaves git-lfs payloads
# as pointer files.
prepare_repo(){
    local repo="${WORK_DIR}/loom" lfs_dir stale_refs ref

    # --no-local forces a real pack transfer. A plain local clone writes
    # .git/objects/info/alternates pointing at this machine, which does not
    # exist on the appliance -- producing a silently corrupt repository.
    git clone --no-hardlinks --no-local --quiet "${CONTEXT_DIR}" "${repo}"
    git -C "${repo}" checkout --force --quiet "tags/${TAG}"

    # Must happen BEFORE `lfs checkout`: without filter.lfs.* configured, the
    # working tree gets real content while the index still holds pointer blobs,
    # so all 138 LFS files show as modified forever.
    git -C "${repo}" lfs install --local

    # Copy this checkout's object cache rather than `git lfs pull`, which needs
    # a reachable remote. Offline, deterministic, and only about 30 MB.
    lfs_dir="$(git -C "${CONTEXT_DIR}" rev-parse --path-format=absolute --git-common-dir)/lfs"
    cp --archive "${lfs_dir}" "${repo}/.git/"
    git -C "${repo}" lfs checkout

    # Nothing in the embedded checkout should depend on which branch the build
    # machine happened to have checked out. A clone brings every ref of the
    # source repository along, so the objects that survive `gc --prune=now`
    # below -- and with them the pack, and with the pack the `loomSrc` store
    # hash -- would otherwise move with a developer's branch tips, giving the
    # same tag a different image on every machine that builds it.
    #
    # One ref is left, which is the one up.sh reads: `git describe
    # --exact-match --tags HEAD` (up.sh:240), against the tag HEAD is already
    # detached at from the checkout above.
    stale_refs="$(git -C "${repo}" for-each-ref --format='%(refname)' refs/heads refs/tags refs/remotes |
        grep --invert-match --line-regexp --fixed-strings "refs/tags/${TAG}" || true)"
    while read -r ref; do
        [[ -n "${ref}" ]] || continue
        git -C "${repo}" update-ref -d "${ref}"
    done <<<"${stale_refs}"

    # for-each-ref does not list this one: it is symbolic, and the branch it
    # names was deleted by the loop above. It is still a file naming the branch
    # the source checkout was on.
    git -C "${repo}" symbolic-ref --delete refs/remotes/origin/HEAD 2>/dev/null || true

    # The object cache copied in above is everything this machine ever fetched,
    # for every branch it ever had. With one ref left, what git-lfs retains is
    # the checkout's own payloads -- the same set on any build host.
    #
    # Runs while origin still exists, because that is how prune decides an
    # object is safe to drop, and takes nothing the box needs: the working tree
    # is already materialised, and verify_repo's pointer-stub check has to pass
    # after this.
    git -C "${repo}" lfs prune --no-verify-remote

    # Nothing on the appliance should point back at a build machine.
    git -C "${repo}" remote remove origin
    git -C "${repo}" reflog expire --expire=now --all
    git -C "${repo}" gc --prune=now --quiet

    # Repack deterministically, so two runs of the same tag produce a
    # byte-identical pack -- and with it the same `loomSrc` store hash, instead
    # of a fresh appliance closure, squashfs and ~1.5 GB image every run. See
    # normalize_git_config for the rest of that story.
    #
    # Both flags are needed:
    #
    #   * `-f` recomputes every delta. Without it repack reuses the deltas it
    #     finds, and those came from the `git clone` above, whose pack-objects
    #     ran multi-threaded on the source repository -- so the nondeterminism
    #     is inherited no matter what this repack is told to do.
    #   * `pack.threads=1` keeps the delta search itself single-threaded. With
    #     several threads the winning candidate depends on how they interleave.
    #
    # Same objects and refs either way; only the encoding is pinned. Verified by
    # running the whole step twice and comparing `nix hash path`.
    git -C "${repo}" -c pack.threads=1 repack -adfq
}

verify_repo(){
    local repo="${WORK_DIR}/loom" described status pointers dirty_count

    described="$(git -C "${repo}" describe --exact-match --tags HEAD)"
    if [[ "${described}" != "${TAG}" ]]; then
        echo >&2 "[!] Error: embedded checkout describes as '${described}', expected '${TAG}'."
        exit 1
    fi

    if [[ ! -d "${repo}/.git/lfs/objects" ]]; then
        echo >&2 "[!] Error: embedded checkout has no git-lfs objects; up.sh:412 would fail on the box."
        exit 1
    fi

    if [[ -e "${repo}/.git/objects/info/alternates" ]]; then
        echo >&2 "[!] Error: embedded checkout has an alternates file pointing outside itself."
        exit 1
    fi

    # The invariant that matters is that no payload is still a pointer stub --
    # that is what breaks bring-up, e.g. a 130-byte text file where the traefik
    # chart should be.
    #
    # Deliberately NOT asserting a clean `git status`: some release tags predate
    # commit 34ba1c77 ("add Git LFS tracking for test assets"), which declared
    # backend/worker/tests/assets/** as LFS while the blobs at those tags are
    # still raw content. Checking such a tag out with the LFS filter active
    # reports those files as modified forever. It is cosmetic -- they are test
    # assets, unused at runtime -- so it is reported, not treated as fatal.
    pointers="$(grep --recursive --files-with-matches --binary-files=without-match \
        --exclude-dir=.git '^version https://git-lfs.github.com/spec/v1' "${repo}" || true)"
    if [[ -n "${pointers}" ]]; then
        echo >&2 "[!] Error: these git-lfs payloads are still pointer stubs:"
        echo >&2 "${pointers}"
        echo >&2 "    Run 'git lfs fetch --all' in your checkout and rebuild."
        exit 1
    fi

    status="$(git -C "${repo}" status --porcelain)"
    if [[ -n "${status}" ]]; then
        dirty_count="$(printf '%s\n' "${status}" | wc --lines)"
        echo "[*] Note: ${dirty_count} file(s) report as modified in the"
        echo "    embedded checkout. This tag predates the LFS conversion of the worker test"
        echo "    assets; they are unused at runtime and bring-up is unaffected."
    fi

    # Canary: this chart is LFS-tracked and cicd/skaffold untars it at deploy
    # time, so a pointer file here means bring-up fails on the box.
    if ! file "${repo}/traefik/traefik-39.0.9.tgz" | grep --quiet gzip; then
        echo >&2 "[!] Error: traefik chart is not a real gzip; git-lfs materialisation is broken."
        exit 1
    fi
}

# Pin the one part of .git whose *content* differs between two runs of the same
# tag.
#
# nixos/default.nix takes `loomSrc` as a filtered `builtins.path` of this
# directory, so a single changed byte gives it a new store hash -- and with it a
# new appliance closure, a new squashfs and a new ~1.5 GB image, every run, for
# a working tree that is bit-for-bit identical. A handful of builds is enough to
# put ten gigabytes of near-duplicates in the store.
#
# The volatile *files* are not handled here. They are excluded by that filter,
# which drops them however often git puts them back -- .git/index, which stores
# mtime, ctime and inode for all ~4000 files; .git/logs; and git-lfs's
# timestamped .git/lfs/logs and randomly-named .git/lfs/tmp scratch
# directories. None of them is read on the box: up.sh only runs `git describe
# --exact-match --tags HEAD` (up.sh:240), which reads refs and objects, and git
# rebuilds an index on demand for anything that does want one.
#
# What a path filter cannot express is a file that has to be there with settled
# contents, which is this one: `git lfs install --local` in prepare_repo writes
# the [filter "lfs"] keys in a nondeterministic order, so the clean/smudge pair
# lands above or below process/required depending on the run.
normalize_git_config(){
    local repo="${WORK_DIR}/loom"

    # Rewritten rather than sorted in place: `git config` owns the file's
    # layout, and re-adding a removed section always appends it in the order
    # given. The values match what `git lfs install` would have written.
    git -C "${repo}" config --local --remove-section filter.lfs
    git -C "${repo}" config --local filter.lfs.clean "git-lfs clean -- %f"
    git -C "${repo}" config --local filter.lfs.smudge "git-lfs smudge -- %f"
    git -C "${repo}" config --local filter.lfs.process "git-lfs filter-process"
    git -C "${repo}" config --local filter.lfs.required true
}

# Sourced from the embedded checkout rather than this one, so the host list
# always matches the tag being shipped. vars.sh stays the single source of truth.
# This is also where ${NAMESPACE} and ${LOOM_CHAT_MODEL} come from -- `source` at
# function scope still assigns globally, and build_image runs after this step.
#
# A value this script wants but the tag's vars.sh has never heard of is a real
# case, not a hypothetical: the stick's Nix code comes from *this* checkout
# (`${CONTEXT_DIR}/nixos`) while the tree it embeds comes from the tag, so the
# console can be newer than the variables it reads. Every such value is
# pre-initialised empty at the top of this script for shellcheck, which is
# exactly what makes the gap silent -- `loomChatModel ""` builds an image whose
# assistant pane announces "Loom assistant on ." and pins opencode to the model
# named `ollama/`. Hence the fallback below rather than an empty --argstr.
generate_loom_hosts(){
    # shellcheck disable=SC1091
    # shellcheck source=../vars.sh
    source "${WORK_DIR}/loom/vars.sh"
    printf '%s\n' "${LOOM_HOSTS_FQDN[@]}" | jq --raw-input . | jq --slurp --compact-output . \
        > "${WORK_DIR}/loom-hosts.json"

    if [[ -z "${LOOM_CHAT_MODEL}" ]]; then
        # Read in a subshell, so this one value crosses over and the tag's
        # other variables -- the host list above included -- stay the tag's.
        LOOM_CHAT_MODEL="$(
            # shellcheck disable=SC1091
            # shellcheck source=../vars.sh
            source "${CONTEXT_DIR}/vars.sh"
            printf '%s' "${LOOM_CHAT_MODEL}"
        )"
        if [[ -z "${LOOM_CHAT_MODEL}" ]]; then
            echo >&2 "[!] Error: neither ${TAG}'s vars.sh nor this checkout's defines"
            echo >&2 "    LOOM_CHAT_MODEL, and the console's assistant pane cannot be"
            echo >&2 "    pinned to a model without it."
            exit 1
        fi
        echo "[!] ${TAG}'s vars.sh defines no LOOM_CHAT_MODEL -- it predates the console"
        echo "    assistant. Pinning the pane to this checkout's value instead:"
        echo "      ${LOOM_CHAT_MODEL}"
        echo "[!] That has to be a model the tag's ollama image bakes in. Check it"
        echo "    against '_llmDefaults.model' in the embedded charts/values.yaml."
    fi
}

build_image(){
    local hosts_json debug_key=''
    hosts_json="$(cat "${WORK_DIR}/loom-hosts.json")"

    # Only the public half, and only when --debug was given. Empty otherwise,
    # which nixos/debug.nix reads as "no debug access" -- its assertion is what
    # catches the case where the flag is on and this is empty anyway.
    if [[ "${DEBUG_ACCESS}" = true ]]; then
        debug_key="$(cat "${DEBUG_KEY_DIR}/id_ed25519.pub")"
    fi

    echo "[*] Building the ${PLATFORM} (${NIX_SYSTEM}) appliance image for ${TAG} on ${SUBNET}.0/24"
    nix-build "${CONTEXT_DIR}/nixos" \
        --attr installerImage \
        --arg nixpkgs "${NIXPKGS}" \
        --arg nixosHardware "${NIXOS_HARDWARE}" \
        --argstr system "${NIX_SYSTEM}" \
        --argstr platform "${PLATFORM}" \
        --arg repoSrc "${WORK_DIR}/loom" \
        --argstr tag "${TAG}" \
        --argstr loomHostsJson "${hosts_json}" \
        --argstr loomNamespace "${NAMESPACE}" \
        --argstr loomChatModel "${LOOM_CHAT_MODEL}" \
        --argstr minikubeIp "${MINIKUBE_IP}" \
        --argstr loomSubnet "${SUBNET}" \
        --argstr loomInterface "${LOOM_INTERFACE}" \
        --arg disableGpu "${DISABLE_GPU}" \
        --arg vmSerialGetty "${VM_SERIAL}" \
        --arg enableWifi "${ENABLE_WIFI}" \
        --argstr wifiSsid "${WIFI_SSID}" \
        --argstr wifiPsk "${WIFI_PSK}" \
        --argstr wifiCountry "${WIFI_COUNTRY}" \
        --argstr wifiInterface "${WIFI_INTERFACE}" \
        --arg debugAccess "${DEBUG_ACCESS}" \
        --argstr debugSshAuthorizedKey "${debug_key}" \
        --arg lockKey "${LOCK_KEY}" \
        --out-link "${IMAGE_LINK}"
}

image_file(){
    # -L is required: the out-link is a symlink into the Nix store, and find
    # does not follow symlinks by default.
    find -L "${IMAGE_LINK}" -name '*.raw' -type f | head --lines=1
}

confirm_flash(){
    local image size answer mounted root_source

    if [[ ! -b "${FLASH_DEVICE}" ]]; then
        echo >&2 "[!] Error: not a block device: ${FLASH_DEVICE}"
        exit 1
    fi

    root_source="$(findmnt --noheadings --output SOURCE --target / | head --lines=1)"
    if [[ "${root_source}" == "${FLASH_DEVICE}"* ]]; then
        echo >&2 "[!] Error: ${FLASH_DEVICE} backs this machine's root filesystem."
        exit 1
    fi

    mounted="$(lsblk --noheadings --raw --output MOUNTPOINTS "${FLASH_DEVICE}" | tr --delete ' \n')"
    if [[ -n "${mounted}" ]]; then
        echo >&2 "[!] Error: ${FLASH_DEVICE} has mounted partitions. Unmount them first."
        exit 1
    fi

    image="$(image_file)"
    size="$(stat --format=%s "${image}")"

    echo
    echo "[!] This will DESTROY ALL DATA on ${FLASH_DEVICE}:"
    lsblk --nodeps --output NAME,SIZE,MODEL,SERIAL,TRAN "${FLASH_DEVICE}"
    echo "[!] Writing $(( size / 1024 / 1024 )) MiB from $(basename "${image}")"
    echo

    if [[ "${ASSUME_YES}" != true ]]; then
        # The device name rather than 'yes', so this cannot be confirmed by
        # muscle memory on the wrong device.
        read -r -p "[?] Type '$(basename "${FLASH_DEVICE}")' to confirm: " answer
        if [[ "${answer}" != "$(basename "${FLASH_DEVICE}")" ]]; then
            echo >&2 "[!] Aborted."
            exit 1
        fi
    fi
}

generate_luks_key(){
    ( umask 077; head --bytes="${KEY_BYTES}" /dev/urandom > "${KEY_DIR}/luks.key" )

    if [[ "${LOCK_KEY}" != true ]]; then
        return
    fi

    # Words rather than the `random_token` alphabet the recovery passphrase and
    # the WiFi PSK use, and not for taste: this one is typed at a stage 1 prompt
    # on a box that has no keyboard layout yet, possibly by somebody who is not
    # the person who flashed the stick. Words survive that; five random
    # characters transcribed off a photograph do not.
    #
    # `diceware` reads its own EFF list and draws from `SystemRandom`, so this is
    # neither a wordlist in this repository nor a hand-rolled index into one.
    KEY_PASSPHRASE="$(diceware --no-caps --delimiter - --num "${LOCK_KEY_WORDS}")"
}

flash_image(){
    local image
    image="$(image_file)"

    echo "[*] Writing ${image} to ${FLASH_DEVICE}"
    sudo dd if="${image}" of="${FLASH_DEVICE}" bs=4M status=progress conv=fsync oflag=direct
    sync

    # Make the kernel adopt the table that was just written.
    #
    # Deliberately NOT `partprobe`, which is what this used to be. The image's
    # GPT describes a disk exactly as large as the image, so on any stick
    # bigger than that parted finds the backup header short of the end of the
    # device and asks what to do about it:
    #
    #   Warning: Not all of the space available to /dev/sdX appears to be used,
    #   you can fix the GPT to use all of the space (an extra N blocks) or
    #   continue with the current setting?
    #
    # That is an interactive prompt in the middle of a step that has to be
    # unattended, and taking its default leaves the kernel on whatever
    # partition table the stick held BEFORE this write. The symptom is the next
    # step reporting no `loom-key` partition on a stick that plainly has one
    # the moment anybody looks at it by hand -- and it is not cosmetic: a stick
    # that is flashed but never given its key installs a box that then never
    # boots again.
    #
    # The backup header really is short of the end, and that is correct: the
    # image is as large as its contents and the installer never uses the tail
    # of the stick. There is nothing to fix, so the right tool is one with no
    # opinion about it.
    #
    # BLKRRPART first: it is the kernel's own re-read of the whole table, it
    # has no opinion about the backup header, and it cannot prompt. It is
    # refused outright while anything still holds a partition, which is the one
    # case `partx` covers -- it updates the kernel's view entry by entry
    # instead. `confirm_flash` already refuses a device with anything mounted,
    # so the fallback is for the holder nobody declared.
    #
    # Neither is trusted on its own. `wait_for_key_partition` below is what
    # actually decides whether the write landed, because the only thing worth
    # checking is that the partition this script is about to write the disk key
    # to is the one that came off this image.
    sudo blockdev --rereadpt "${FLASH_DEVICE}" 2> /dev/null \
        || sudo partx --update "${FLASH_DEVICE}" > /dev/null
    sudo udevadm settle

    wait_for_key_partition
}

# Block until the partition written above is there, or say why it is not.
#
# `key_partition` reads the table off the disk, so in practice this returns on
# the first pass -- the kernel populates sysfs synchronously when it re-reads.
# The loop is insurance against a USB bridge that is still settling, and it
# costs nothing on the run where it is not needed.
wait_for_key_partition(){
    local waited=0 found

    # Assigned rather than tested inline, for the reason resolve_tag gives at
    # the same place: a function called inside a condition runs with `set -e`
    # switched off, and shellcheck's `-o all` says so.
    while (( waited < KEY_PARTITION_TIMEOUT )); do
        found="$(key_partition)"
        if [[ -n "${found}" ]]; then
            return 0
        fi
        sleep 1
        waited=$(( waited + 1 ))
    done

    echo >&2 "[!] Error: no '${KEY_PARTLABEL}' partition on ${FLASH_DEVICE}"
    echo >&2 "    ${KEY_PARTITION_TIMEOUT}s after writing the image."
    echo >&2 "    The partition table on the device reads:"
    sudo partx --show --output NR,SIZE,NAME "${FLASH_DEVICE}" >&2 || true
    echo >&2 "    Three partitions named loom-live-esp, loom-live-store and ${KEY_PARTLABEL} were"
    echo >&2 "    just written. If the table above is the one this stick had before, the write"
    echo >&2 "    did not land: unplug the stick, plug it back in, and run the same command"
    echo >&2 "    again -- the image is already built, so it will not be rebuilt."
    exit 1
}

# Resolved on the flashed device rather than through /dev/disk/by-partlabel, so
# a second Loom stick in another port cannot be written to by mistake.
#
# Read off the partition table itself, NOT out of `lsblk`'s PARTLABEL column,
# which is where this used to look. That column comes from udev's database, and
# udev populates it asynchronously long after the kernel has the table: on a
# freshly flashed stick the partitions are all correct and visible -- right
# count, right sizes -- while every PARTLABEL is still empty, and they stay
# empty for longer than any timeout worth having. Re-plugging the stick fixes
# it, which is a fine diagnosis and a terrible build step.
#
# `partx --show` parses the GPT on the device, so it answers from the same bytes
# `dd` just wrote and needs nothing to have settled.
key_partition(){
    local number

    number="$(sudo partx --show --noheadings --raw --output NR,NAME "${FLASH_DEVICE}" \
        | awk --assign label="${KEY_PARTLABEL}" '$2 == label { print $1 }' \
        | head --lines=1)"
    if [[ -z "${number}" ]]; then
        return 0
    fi

    partition_path "${number}"
}

# A partition number on FLASH_DEVICE, as a device node.
#
# Asked of the kernel rather than assembled, because the rule differs by
# transport: /dev/sdb + 3 is /dev/sdb3, but /dev/nvme0n1 + 3 is /dev/nvme0n1p3
# and /dev/mmcblk0 + 3 is /dev/mmcblk0p3. Every partition's own sysfs directory
# already carries its number, so there is nothing here to encode and get wrong.
#
# Under the disk's own directory rather than /sys/class/block, where a glob on
# the disk name would also match an unrelated disk (`sdb*` catches `sdba`) whose
# partition numbers would collide.
partition_path(){
    local number="${1}" disk entry found
    disk="$(basename "${FLASH_DEVICE}")"

    for entry in "/sys/block/${disk}/${disk}"*/partition; do
        if [[ ! -r "${entry}" ]]; then
            continue
        fi
        read -r found < "${entry}"
        if [[ "${found}" == "${number}" ]]; then
            printf '/dev/%s' "$(basename "$(dirname "${entry}")")"
            return 0
        fi
    done
}

write_key_partition(){
    local key_part
    key_part="$(key_partition)"

    if [[ -z "${key_part}" ]]; then
        echo >&2 "[!] Error: no '${KEY_PARTLABEL}' partition on ${FLASH_DEVICE} after flashing."
        exit 1
    fi

    if [[ "${LOCK_KEY}" = true ]]; then
        write_locked_key_partition "${key_part}"
        return
    fi

    echo "[*] Writing the LUKS key to ${key_part}"
    sudo dd if="${KEY_DIR}/luks.key" of="${key_part}" bs="${KEY_BYTES}" count=1 conv=fsync status=none
    sync
}

# --lock-key: the partition becomes a container and the key goes inside it.
#
# argon2id, deliberately unlike the root container the installer formats with
# pbkdf2 at 1000 iterations. The two are formatted for opposite inputs: that one
# is opened with 4096 bytes of /dev/urandom, where stretching buys nothing, and
# this one is opened with something a human typed, where stretching is the entire
# defence.
#
# The cost is pinned rather than benchmarked, which is what cryptsetup does left
# to itself. Benchmarking is wrong twice here: it measures the *build host*, and
# the container is opened on the box and in its initrd -- so a roomy build host
# would pick a memory cost a smaller box cannot afford, and stage 1 would fail to
# unlock a stick that verified perfectly. Pinning also makes two sticks flashed
# on two machines the same strength.
#
# 1 GiB and four passes is what cryptsetup picks on an ordinary machine anyway,
# and every platform in nixos/platforms/ has many times that much RAM free in
# stage 1. `--pbkdf-force-iterations` is what skips the benchmark entirely.
write_locked_key_partition(){
    local key_part="${1}"

    echo "[*] Creating the LUKS key container on ${key_part}"
    printf '%s' "${KEY_PASSPHRASE}" | sudo cryptsetup luksFormat \
        --type luks2 \
        --batch-mode \
        --pbkdf argon2id \
        --pbkdf-force-iterations 4 \
        --pbkdf-memory 1048576 \
        --pbkdf-parallel 4 \
        --key-file - \
        "${key_part}"

    printf '%s' "${KEY_PASSPHRASE}" | sudo cryptsetup open \
        --type luks2 \
        --key-file - \
        "${key_part}" "${KEYSTORE_MAPPING}"

    echo "[*] Writing the LUKS key into the container"
    sudo dd if="${KEY_DIR}/luks.key" of="/dev/mapper/${KEYSTORE_MAPPING}" \
        bs="${KEY_BYTES}" count=1 conv=fsync status=none
    sync
    sudo cryptsetup close "${KEYSTORE_MAPPING}"
}

verify_flash(){
    local key_part label names

    # From the partition table, for the reason `key_partition` gives: `lsblk`'s
    # PARTLABEL column is udev's answer, and udev has not necessarily caught up
    # with a stick written seconds ago.
    names="$(sudo partx --show --noheadings --raw --output NAME "${FLASH_DEVICE}")"

    for label in loom-live-esp loom-live-store "${KEY_PARTLABEL}"; do
        if ! grep --quiet --line-regexp --fixed-strings "${label}" <<< "${names}"; then
            echo >&2 "[!] Error: partition '${label}' is missing from ${FLASH_DEVICE}."
            echo >&2 "    The partition table on the device reads:"
            sudo partx --show --output NR,SIZE,NAME "${FLASH_DEVICE}" >&2 || true
            exit 1
        fi
    done

    # Read the key back. A stick whose key partition did not take would install
    # fine and then never boot again, which is a miserable thing to discover in
    # the field.
    key_part="$(key_partition)"
    if [[ "${LOCK_KEY}" = true ]]; then
        # Through the container, which checks the passphrase and the key together:
        # this is the same sequence stage 1 will run, so a stick that passes here
        # is one that boots.
        printf '%s' "${KEY_PASSPHRASE}" | sudo cryptsetup open \
            --type luks2 \
            --key-file - \
            "${key_part}" "${KEYSTORE_MAPPING}"
        sudo dd if="/dev/mapper/${KEYSTORE_MAPPING}" of="${KEY_DIR}/readback.key" \
            bs="${KEY_BYTES}" count=1 status=none
        sudo cryptsetup close "${KEYSTORE_MAPPING}"
    else
        sudo dd if="${key_part}" of="${KEY_DIR}/readback.key" bs="${KEY_BYTES}" count=1 status=none
    fi

    if ! cmp --silent "${KEY_DIR}/luks.key" "${KEY_DIR}/readback.key"; then
        echo >&2 "[!] Error: the key read back from ${key_part} does not match what was written."
        exit 1
    fi
    echo "[*] Key verified on ${key_part}"
}

backup_luks_key(){
    if [[ -z "${KEY_BACKUP}" ]]; then
        echo
        echo "[!] The LUKS key exists on exactly one physical object: this USB stick."
        echo "[!] If it is lost or damaged, the box's data is unrecoverable unless"
        echo "[!] someone wrote down the recovery passphrase shown after installation."
        echo "[!] Pass --key-backup FILE to keep a copy."
        return
    fi

    # Never inside the repository, where `git add -A` could pick it up.
    assert_secret_path "${KEY_BACKUP}" "the LUKS key"

    install --mode=0400 "${KEY_DIR}/luks.key" "${KEY_BACKUP}"
    echo "[*] LUKS key backed up to ${KEY_BACKUP} (mode 0400). Store it away from the box."

    if [[ "${LOCK_KEY}" = true ]]; then
        # Worth saying plainly: this file is the key itself, not the container
        # around it, so it opens the box's disk with no passphrase involved. It
        # is the one copy of the key that --lock-key does not cover.
        echo "[!] That file is the raw key. It unlocks the box without the stick and"
        echo "[!] without the passphrase -- keep it somewhere that reflects it."
    fi
}

backup_key_passphrase(){
    if [[ "${LOCK_KEY}" != true ]]; then
        return
    fi

    if [[ -z "${LOCK_KEY_OUT}" ]]; then
        echo
        echo "[!] The key passphrase is printed below and stored nowhere. Write it"
        echo "[!] down before this terminal scrolls: without it the stick is inert,"
        echo "[!] and the only way left into the box is the recovery passphrase the"
        echo "[!] installer prints after it runs."
        echo "[!] Pass --lock-key-out FILE to keep a copy."
        return
    fi

    # Checked again at the point of writing, not only in resolve_lock_key: a
    # secret is worth refusing twice, and these two run minutes apart.
    assert_secret_path "${LOCK_KEY_OUT}" "--lock-key-out"

    ( umask 077; printf '%s\n' "${KEY_PASSPHRASE}" > "${LOCK_KEY_OUT}" )
    chmod 0400 "${LOCK_KEY_OUT}"
    echo "[*] Key passphrase written to ${LOCK_KEY_OUT} (mode 0400)."
    echo "[*] Keep it apart from the stick -- together they are one factor, not two."
}

report(){
    local image checksum gpu

    image="$(image_file)"
    gpu="$(gpu_report)"
    checksum="$(sha256sum "${KEY_DIR}/luks.key" 2>/dev/null | cut --delimiter=' ' --fields=1 || echo 'not generated')"

    echo
    echo "[*] Appliance image ready"
    echo "      image     : ${image}"
    echo "      loom tag  : ${TAG}"
    echo "      platform  : ${PLATFORM}"
    echo "      system    : ${NIX_SYSTEM}"
    echo "      subnet    : ${SUBNET}.0/24 (box at ${SUBNET}.1, DHCP ${SUBNET}.100-200)"
    echo "      interface : loom0${LOOM_INTERFACE:+ (renamed from ${LOOM_INTERFACE})}"
    echo "      gpu       : ${gpu}"
    echo "      debug     : ${DEBUG_ACCESS}"
    echo "      key lock  : ${LOCK_KEY}"
    echo "      wifi      : ${ENABLE_WIFI}"
    if [[ "${ENABLE_WIFI}" = true ]]; then
        echo "      ssid      : ${WIFI_SSID}"
        echo "      wifi psk  : ${WIFI_PSK}"
        if [[ -n "${WIFI_COUNTRY}" ]]; then
            echo "      wifi band : 5GHz ch36, country ${WIFI_COUNTRY}"
        else
            echo "      wifi band : 2.4GHz ch6, no country code"
        fi
        echo
        echo "[!] This box will serve Loom over the air to anyone within range who has"
        echo "[!] that passphrase. Loom has no user management and its frontend is not"
        echo "[!] an authentication boundary, so the passphrase is the only thing between"
        echo "[!] the indexed data and a stranger in the car park. It is also printed on"
        echo "[!] the box's login screen, as a QR code, for anyone standing at the monitor."
        echo "[!] Do not cable a wifi-enabled box into a network you do not own: the radio"
        echo "[!] and the wired port are bridged, so it becomes an open door onto that LAN."
    fi
    if [[ "${DEBUG_ACCESS}" = true ]]; then
        echo
        echo "[*] Debug access. The key that opens this image:"
        echo "      key dir   : ${DEBUG_KEY_DIR}"
        echo "      on the box: ssh -F ${DEBUG_KEY_DIR}/ssh_config loom-appliance"
        echo "      in a VM   : ssh -F ${DEBUG_KEY_DIR}/ssh_config.vm loom-appliance"
        echo "      bundle    : ssh -F ... loom-appliance loom-debug-bundle"
        echo
        echo "[!] This image is NOT an appliance anybody may be handed. It runs an SSH"
        echo "[!] server, and the key above is root on the box -- the operator account is"
        echo "[!] in 'wheel' with passwordless sudo. Loom has no user management behind"
        echo "[!] that, so whoever holds the key holds the indexed corpus."
        echo "[!] The box says so itself, in red, on its login screen, in the motd and on"
        echo "[!] the second line of its boot menu entry -- and this image file carries"
        echo "[!] '-debug' in its name so two .raw files in a drawer cannot be mixed up."
        echo "[!] It also boots without the splash and its USB key guard only warns"
        echo "[!] instead of powering off, so it does not behave like a real stick."
        echo "[!] Delete ${DEBUG_KEY_DIR} when you are done, and wipe the box."
    fi
    if [[ -n "${FLASH_DEVICE}" ]] && [[ "${LOCK_KEY}" = true ]]; then
        echo "      flashed to: ${FLASH_DEVICE}"
        echo "      key sha256: ${checksum}"
        echo "      key phrase: ${KEY_PASSPHRASE}"
        echo
        echo "[*] Boot the box from this stick. It will NOT install by itself: the key"
        echo "[*] is passphrase-locked, so the installer waits at its menu for somebody"
        echo "[*] to choose Install and type the passphrase above."
        echo "[*] The stick must stay plugged in afterwards -- it holds the disk key --"
        echo "[*] and every boot from then on stops and asks for that passphrase. This"
        echo "[*] box cannot come back on its own after a power cut."
        echo "[*] Keep the passphrase somewhere other than with the stick. Together they"
        echo "[*] are one factor; apart they are two, which is the point of --lock-key."
    elif [[ -n "${FLASH_DEVICE}" ]]; then
        echo "      flashed to: ${FLASH_DEVICE}"
        echo "      key sha256: ${checksum}"
        echo
        echo "[*] Boot the box from this stick and leave it alone. It counts down for"
        echo "[*] 60 seconds and then installs by itself, pooling every internal NVMe"
        echo "[*] into one encrypted volume. Press any key during the countdown for a menu."
        echo "[*] The stick must stay plugged in afterwards: it holds the disk key."
    elif [[ "${VM_SERIAL}" = true ]]; then
        echo
        echo "[!] Built with --vm-serial: the installer and the box it installs both carry"
        echo "[!] a getty on ttyS0. That is one unit more than a real stick has, so do not"
        echo "[!] flash this image -- --flash refuses it, and this line is here for the copy"
        echo "[!] somebody keeps. Boot it with: appliance-vm installer --serial"
    else
        echo
        echo "[*] Flash it with: build-appliance-image --flash /dev/sdX"
    fi
}

#
# Usage
#

usage(){
    echo "usage: $0 [<options>]"
    echo "  -h|--help                     show this help"
    echo "  -v|--verbose                  show verbose output"
    echo "  -t|--tag TAG                  Loom tag to embed (default: the newest tag)"
    echo "  -o|--output OUTPUT_DIR        where to place the image (default: .appliance-build)"
    echo "  -f|--flash DEVICE             flash to DEVICE, destroying all data on it"
    echo "  -k|--key-backup FILE          also write the generated LUKS key to FILE"
    echo "  --lock-key                    put the LUKS key inside a passphrase-locked container"
    echo "                                on the stick instead of writing it raw, and generate"
    echo "                                the word passphrase. The stick stops being a bearer"
    echo "                                token -- holding it is no longer enough. Costs"
    echo "                                unattended boot: every boot stops at a prompt, and"
    echo "                                the installer will not run unattended either."
    echo "  --lock-key-words N            how many words in that passphrase (default:"
    echo "                                ${LOCK_KEY_WORDS_DEFAULT}, minimum ${LOCK_KEY_MIN_WORDS})"
    echo "  --lock-key-out FILE           also write the key passphrase to FILE. Must not be"
    echo "                                the same file as --key-backup: one file holding both"
    echo "                                factors is no better than neither."
    echo "  --vm-serial                   add a getty on ttyS0 to the installer and to the box"
    echo "                                it installs, so a VM can be driven from a terminal that"
    echo "                                copies and pastes. For 'appliance-vm installer --serial';"
    echo "                                refused with --flash, because this is not a stick image."
    echo "  --debug                       run an SSH server on the box, keyed to a keypair"
    echo "                                generated here and left in a temp directory this"
    echo "                                prints. Takes back the appliance's 'no remote access'"
    echo "                                guarantee, so the box says DEBUG in red on its login"
    echo "                                screen, in its boot menu and in the motd, and the"
    echo "                                image file is named '-debug'. Never hand one to"
    echo "                                anybody. Refused when \$CI is set."
    echo "  --no-gpu                      build CPU-only for a platform that offloads to a GPU."
    echo "                                There is no --gpu: the GPU is a property of the box and"
    echo "                                is declared per platform. Use this when the box turns out"
    echo "                                not to see its own GPU, which otherwise stops Loom dead."
    echo "  -p|--platform PLATFORM        box to build for: ${KNOWN_PLATFORMS[*]} (default: ${PLATFORM})"
    echo "  -s|--system SYSTEM            nix system to build (default: the platform's)"
    echo "  -i|--interface INTERFACE      pin the appliance NIC by the name the box reports"
    echo "                                (enp2s0, not eth0) instead of letting the platform"
    echo "                                match it. Renamed to loom0 either way. Rarely needed:"
    echo "                                an unmatched box claims a wired port on its own."
    echo "  --subnet A.B.C                appliance subnet prefix (default: random 10.x.y)"
    echo "  --wifi                        also run an access point, bridged onto the wired"
    echo "                                port. Radios are disabled without this."
    echo "  --wifi-ssid SSID              network name (default: generated 'loom-xxxx')"
    echo "  --wifi-psk PSK                WPA passphrase (default: generated)"
    echo "  --wifi-country CC             ISO country code; moves the AP to 5GHz. Without it"
    echo "                                the AP stays on 2.4GHz, the only band an AP may"
    echo "                                beacon on with no country code set."
    echo "  --wifi-interface INTERFACE    pin the radio by name instead of letting the"
    echo "                                platform match it (renamed to loomwl0 either way)"
    echo "  --minikube-ip MINIKUBE_IP     address '*.loom' resolves to on the box (default: ${MINIKUBE_IP})"
    echo "  --nixpkgs NIXPKGS             nixpkgs source (required; 'build-appliance-image' passes it)"
    echo "  --nixos-hardware PATH         nixos-hardware source (required; passed the same way)"
    echo "  -y|--yes                      do not ask for confirmation"
    echo "  --allow-cross                 allow building for a system other than the host"
    echo "  --skip-STEP                   skip step STEP, e.g. --skip-validate_environment to build"
    echo "                                past the preflight checks. Later steps assume the earlier"
    echo "                                ones ran, so this is a debugging escape hatch, not a"
    echo "                                supported way to build a stick. The steps, in order:"
    printf '                                  %s\n' "${STEPS[@]}"
    echo "                                and with --flash, between build_image and report:"
    printf '                                  %s\n' "${FLASH_STEPS[@]}"
}

#
# Atexit handler
#

atexit(){
    if [[ -n "${KEY_DIR}" && -d "${KEY_DIR}" ]]; then
        rm --recursive --force "${KEY_DIR}"
    fi
    if [[ -n "${WORK_DIR}" && -d "${WORK_DIR}" ]]; then
        rm --recursive --force "${WORK_DIR}"
    fi
    # DEBUG_KEY_DIR is deliberately absent from this list. Unlike the two above
    # it is not scratch: it holds the only copy of the private key that opens
    # the image this run just built, and deleting it here would make --debug a
    # flag that produces an unreachable box. `report` prints where it is, and
    # removing it is the operator's call.
    echo "[*] Exiting.."
}
trap atexit EXIT

#
# Argument parsing
#

ARGS=()
while [[ $# -gt 0 ]]; do
    case "${1}" in
        -h|--help)
            usage
            trap - EXIT
            exit 0
        ;;
        -v|--verbose)
            VERBOSE=true
            shift
        ;;
        -t|--tag)
            shift
            TAG="${1?Missing TAG}"
            shift
        ;;
        -o|--output)
            shift
            OUTPUT_DIR="${1?Missing OUTPUT_DIR}"
            shift
        ;;
        -f|--flash)
            shift
            FLASH_DEVICE="${1?Missing DEVICE}"
            shift
        ;;
        -k|--key-backup)
            shift
            KEY_BACKUP="${1?Missing FILE}"
            shift
        ;;
        --lock-key)
            LOCK_KEY=true
            shift
        ;;
        --lock-key-words)
            shift
            LOCK_KEY_WORDS="${1?Missing N}"
            shift
        ;;
        --lock-key-out)
            shift
            LOCK_KEY_OUT="${1?Missing FILE}"
            shift
        ;;
        --vm-serial)
            VM_SERIAL=true
            shift
        ;;
        --debug)
            DEBUG_ACCESS=true
            shift
        ;;
        --no-gpu)
            # There is no --gpu to go with this. Whether a box has a usable GPU
            # is a property of the hardware and is declared once, in
            # nixos/platforms/<id>.nix; asking for one the box does not have
            # would only produce a stick that fails on first boot.
            #
            # The opt-out is here because the declaration can be wrong in the
            # other direction, and that failure is the expensive one: up.sh
            # counts GPUs through the vendor's SMI tool and hard-exits when it
            # finds none, so a box where ROCm does not enumerate serves nothing
            # at all, with no remote access to repair it. Rebuild with this and
            # the same stick comes back CPU-only.
            DISABLE_GPU=true
            shift
        ;;
        -p|--platform)
            shift
            PLATFORM="${1?Missing PLATFORM}"
            # Matched against the list rather than by calling platform_system,
            # which in a condition would silently disable `set -e` inside it.
            case " ${KNOWN_PLATFORMS[*]} " in
                *" ${PLATFORM} "*)
                    :
                ;;
                *)
                    echo >&2 "[!] Error: unknown platform: ${PLATFORM}"
                    echo >&2 "    Known platforms: ${KNOWN_PLATFORMS[*]}"
                    exit 1
                ;;
            esac
            shift
        ;;
        -s|--system)
            shift
            NIX_SYSTEM="${1?Missing SYSTEM}"
            shift
        ;;
        -i|--interface)
            shift
            LOOM_INTERFACE="${1?Missing INTERFACE}"
            shift
        ;;
        --subnet)
            shift
            SUBNET="${1?Missing SUBNET}"
            shift
        ;;
        --wifi)
            ENABLE_WIFI=true
            shift
        ;;
        --wifi-ssid)
            shift
            WIFI_SSID="${1?Missing SSID}"
            shift
        ;;
        --wifi-psk)
            shift
            WIFI_PSK="${1?Missing PSK}"
            shift
        ;;
        --wifi-country)
            shift
            WIFI_COUNTRY="${1?Missing COUNTRY}"
            shift
        ;;
        --wifi-interface)
            shift
            WIFI_INTERFACE="${1?Missing INTERFACE}"
            shift
        ;;
        --minikube-ip)
            shift
            MINIKUBE_IP="${1?Missing MINIKUBE_IP}"
            shift
        ;;
        --nixpkgs)
            shift
            NIXPKGS="${1?Missing NIXPKGS}"
            shift
        ;;
        --nixos-hardware)
            shift
            NIXOS_HARDWARE="${1?Missing NIXOS_HARDWARE}"
            shift
        ;;
        -y|--yes)
            ASSUME_YES=true
            shift
        ;;
        --allow-cross)
            ALLOW_CROSS=true
            shift
        ;;
        --skip-*)
            SKIP+=("${1}")
            shift
        ;;
        *)
            ARGS+=("${1}")
            shift
        ;;
    esac
done

#
# Main
#

if [[ "${VERBOSE}" = true ]]; then
    set -x
fi

# --system is the raw override; otherwise the platform decides. Resolved here
# rather than at declaration time so that --platform and --system may be given
# in either order.
if [[ -z "${NIX_SYSTEM}" ]]; then
    NIX_SYSTEM="$(platform_system "${PLATFORM}")"
fi

PLATFORM_GPU="$(platform_gpu "${PLATFORM}")"

# Same reason --platform is checked against a list: catch the flag that cannot
# do anything here, rather than building for an hour and handing over a stick
# that is identical to the one the operator would have got anyway.
if [[ "${DISABLE_GPU}" = true && -z "${PLATFORM_GPU}" ]]; then
    echo >&2 "[!] Error: platform '${PLATFORM}' is already CPU-only; --no-gpu has nothing to disable."
    exit 1
fi

# A stick with a getty on its serial port is not the stick this script exists to
# produce, and the difference is invisible once it has been written: nothing on
# the label, nothing on the console, nothing in `report` after the fact. Refuse
# the combination rather than rely on whoever typed it to remember.
if [[ "${VM_SERIAL}" = true && -n "${FLASH_DEVICE}" ]]; then
    echo >&2 "[!] Error: --vm-serial builds an image for a VM, not for a stick."
    echo >&2 "    It adds a getty on ttyS0 to the installer and to the box it installs."
    echo >&2 "    Drop --flash to keep the image, or drop --vm-serial to flash one."
    exit 1
fi

# A pipeline has no business building an image with a way in, and no way to be
# told about one: `report` prints the key directory to a log nobody reads, and
# the runner deletes it minutes later -- so the artifact would be a stick that
# is remotely accessible and that nobody holds the key to. Refused outright
# rather than warned about, because there is no case where it is what was meant.
if [[ "${DEBUG_ACCESS}" = true && -n "${CI:-}" ]]; then
    echo >&2 "[!] Error: refusing to build a --debug image in CI (\$CI is set)."
    echo >&2 "    A debug image runs an SSH server, and the key that opens it would be"
    echo >&2 "    thrown away with the runner. Build one on the machine you will debug from."
    exit 1
fi

# Unlike --vm-serial this IS allowed to be flashed -- debugging real hardware is
# most of the point -- but not silently. Flashing is the step that turns a file
# somebody can delete into a stick that walks out of the building.
if [[ "${DEBUG_ACCESS}" = true && -n "${FLASH_DEVICE}" && "${ASSUME_YES}" != true ]]; then
    echo "[!] --debug and --flash together: this writes a stick that runs an SSH server."
    echo "[!] The key is generated here and is root on any box installed from it."
    echo "[!] Do not let it leave the bench, and wipe the box afterwards."
    read -r -p "[?] Flash a debug stick? [y/N] " answer
    if [[ "${answer}" != "y" && "${answer}" != "Y" ]]; then
        echo >&2 "[!] Aborted."
        exit 1
    fi
fi

# Resolved here rather than at declaration time, for the same reason NIX_SYSTEM
# is: --debug and --output may be given in either order.
IMAGE_LINK="${OUTPUT_DIR}/appliance-image"
if [[ "${DEBUG_ACCESS}" = true ]]; then
    IMAGE_LINK+="-debug"
fi

if [[ -n "${FLASH_DEVICE}" ]]; then
    # report last, so it can describe what was flashed.
    STEPS=( "${STEPS[@]:0:${#STEPS[@]}-1}" "${FLASH_STEPS[@]}" report )
fi

# execute steps
for step in "${STEPS[@]}"; do
    if [[ "${SKIP[*]}" == *"--skip-${step}"* ]]; then
        echo "[*] Skipping: ${step}"
        continue
    fi
    echo "[*] Running: ${step}"
    "${step}" "${ARGS[@]}"
done
