{
 "title": "API Requests",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(http_server_active_requests,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Method",
   "type": "piechart",
   "gridPos": { "h": 32, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_method) (http_server_active_requests{instance=~\"$instance\"})",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Request Durations",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 22, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_target) (rate(http_server_duration_milliseconds_bucket{instance=\"$instance\", http_target!=\"\"}[$__rate_interval]))) > 0",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Response Sizes",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 22, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_target) (rate(http_server_response_size_bytes_bucket{instance=\"$instance\", http_target!=\"\"}[$__rate_interval]))) > 0",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Request Sizes",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 22, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_target) (rate(http_server_request_size_bytes_bucket{instance=\"$instance\", http_target!=\"\"}[$__rate_interval]))) > 0",
     "legendFormat": "{{http_target}}"
    }
   ]
  }
 ]
}