{
 "title": "Cache Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cache_entries_count_entry,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Count Entries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cache_entries_count_entry{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cache_mem_size_byte{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cache_hits_count_hit{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Misses",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cache_miss_count_miss{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}