{
 "title": "Cluster monitoring",
 "description": "Cluster monitoring with Prometheus and cAdvisor with node selection",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_cpu_user_seconds_total, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"}, instance)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{hostname!~\"$instance\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{instance=~\"$instance\", namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(\n    container_last_seen{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}\n    > (time() - 60)\n)\n\n"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"})\n/ count(container_memory_working_set_bytes{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])\n) / count(container_cpu_usage_seconds_total{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "I/O Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "I/O Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{job=~\"$job\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}