{
 "title": "Container resources monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests,container)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{container=~\"$container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits{resource=\"cpu\",container=~\"$container\",pod=~\"$pod\"})",
     "legendFormat": "CPU Limits"
    },
    {
     "expr": "avg by (container)(kube_pod_container_resource_requests{resource=\"cpu\",container=~\"$container\",pod=~\"$pod\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"$container\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits{resource=\"memory\",container=~\"$container\",pod=~\"$pod\"})",
     "legendFormat": "Memory limit"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests{resource=\"memory\",container=~\"$container\",pod=~\"$pod\"})",
     "legendFormat": "Memory request"
    },
    {
     "expr": "container_memory_usage_bytes{container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restart Reasons",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (reason) (kube_pod_container_status_last_terminated_reason{container=~\"$container\",pod=~\"$pod\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=~\".*$container.*\"}",
     "legendFormat": "PVC Limits: {{persistentvolumeclaim}}"
    },
    {
     "expr": " kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$container.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}