{
 "title": "Gotenberg",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Libreoffice Request Queue",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gotenberg_libreoffice_requests_queue_size",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chrome Request Queue",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gotenberg_chromium_requests_queue_size",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Libreoffice Restart",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "gotenberg_libreoffice_restarts_count",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chrome Restart",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "gotenberg_chromium_restarts_count",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}