{
 "title": "K8s Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RAM Usage (working set)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container) (\n    avg by (container, pod, node) (container_memory_working_set_bytes{container!=\"\"})\n    / on(container, pod, node) \n    max by (container, pod, node, resource) (kube_pod_container_resource_limits{resource=\"memory\"})\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace, volume) (\n  label_replace(\n    kubelet_volume_stats_used_bytes,\n    \"volume\",\n    \"$1\",\n    \"persistentvolumeclaim\",\n    \"(.+)-[0-9]+\"\n  )\n)\n/\nsum by (namespace, volume) (\n  label_replace(\n    kubelet_volume_stats_capacity_bytes,\n    \"volume\",\n    \"$1\",\n    \"persistentvolumeclaim\",\n    \"(.+)-[0-9]+\"\n  )\n)",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container) (\n    avg by (container, pod, node) (rate(container_cpu_usage_seconds_total{container!=\"\"}[5m]))\n    / on(container, pod, node) \n    max by (container, pod, node, resource) (kube_pod_container_resource_limits{resource=\"cpu\"})\n)",
     "legendFormat": "{{container}} "
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, container, reason) (\n  increase(kube_pod_container_status_restarts_total[24h])\n  * on (namespace, container, pod)\n  group_left(reason) (\n    topk(1, kube_pod_container_status_last_terminated_reason == 1) \n    by (namespace, container, pod)\n  )\n)",
     "legendFormat": "{{container}}: {{reason}}"
    }
   ]
  },
  {
   "title": "HPA Replicas",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (horizontalpodautoscaler) (kube_horizontalpodautoscaler_status_current_replicas)\n/ sum by (horizontalpodautoscaler) (kube_horizontalpodautoscaler_spec_max_replicas)",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container) (\n  container_memory_working_set_bytes{container!=\"\"}\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{container!=\"\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}