apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-open-webui
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  replicas: {{ .Values.open_webui.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-open-webui
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-open-webui
    spec:
      containers:
        - name: open-webui
          image: {{ .Values.image.registry }}/{{ .Values.open_webui.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.open_webui.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: openwebui
              containerPort: {{ .Values.open_webui.service.port }}
          env:
            - name: OLLAMA_BASE_URL
              value: http://{{ include "app.fullname" . }}-ollama:{{ .Values.ollama.service.port }}
            - name: WEBUI_AUTH
              value: {{ .Values.open_webui.env.WEBUI_AUTH | quote }}
            - name: ENABLE_SIGNUP
              value: {{ .Values.open_webui.env.ENABLE_SIGNUP | quote }}
            - name: DEFAULT_MODELS
              value: {{ .Values.llm.model | quote }}
          {{- if .Values.open_webui.resources }}
          resources: {{- toYaml .Values.open_webui.resources | nindent 12 }}
          {{- end }}