{{- if .Values.open_webui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-open-webui
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: open-webui
  annotations:
    {{- toYaml .Values.open_webui.ingress.annotations | nindent 4 }}
    {{- if .Values.certificate.requireClientCert }}
    traefik.ingress.kubernetes.io/router.tls.options: {{ .Release.Namespace }}-{{ include "app.fullname" . }}-mtls@kubernetescrd
    {{- end }}
spec:
  ingressClassName: {{ .Values.open_webui.ingress.className }}
  rules:
    - host: open-webui.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}-open-webui
                port:
                  number: {{ .Values.open_webui.service.port }}
  {{- if .Values.open_webui.ingress.tls.enabled }}
  tls:
    - secretName: {{ include "app.fullname" . }}-certificate
      hosts:
        - open-webui.{{ .Values.domain }}
  {{- end }}
{{- end }}
