{{- if .Values.fluentd.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}-fluentd
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "fluentd") | nindent 4 }}
    app.kubernetes.io/component: monitoring
  {{- with include "app.annotations.custom" (dict "context" . "component" "fluentd") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
