apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-tika-imagemagick-policy
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "tika") | nindent 4 }}
    app.kubernetes.io/component: tika
  {{- with include "app.annotations.custom" (dict "context" . "component" "tika") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  policy.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE policymap [
      <!ELEMENT policymap (policy)*>
      <!ATTLIST policymap xmlns CDATA #FIXED ''>
      <!ELEMENT policy EMPTY>
      <!ATTLIST policy xmlns CDATA #FIXED '' domain NMTOKEN #REQUIRED
        name NMTOKEN #IMPLIED pattern CDATA #IMPLIED rights NMTOKEN #IMPLIED
        stealth NMTOKEN #IMPLIED value CDATA #IMPLIED>
    ]>
    <policymap>
      <!-- <policy domain="resource" name="temporary-path" value="/tmp"/> -->
      <policy domain="resource" name="memory" value="256MiB" />
      <policy domain="resource" name="map" value="512MiB" />
      <policy domain="resource" name="width" value="16KP" />
      <policy domain="resource" name="height" value="16KP" />
      <!-- <policy domain="resource" name="list-length" value="128"/> -->
      <policy domain="resource" name="area" value="128MP" />
      <policy domain="resource" name="disk" value="1GiB" />
      <!-- <policy domain="resource" name="file" value="768"/> -->
      <!-- <policy domain="resource" name="thread" value="4"/> -->
      <!-- <policy domain="resource" name="throttle" value="0"/> -->
      <policy domain="resource" name="time" value="{{ .Values.pipeline.imagemagick_timeout_seconds | default 600 }}"/>
      <!-- <policy domain="coder" rights="none" pattern="MVG" /> -->
      <!-- <policy domain="module" rights="none" pattern="{PS,PDF,XPS}" /> -->
      <!-- <policy domain="path" rights="none" pattern="@*" /> -->
      <!-- <policy domain="cache" name="memory-map" value="anonymous"/> -->
      <!-- <policy domain="cache" name="synchronize" value="True"/> -->
      <!-- <policy domain="cache" name="shared-secret" value="passphrase" stealth="true"/> -->
      <!-- <policy domain="system" name="max-memory-request" value="256MiB"/> -->
      <!-- <policy domain="system" name="shred" value="2"/> -->
      <!-- <policy domain="system" name="precision" value="6"/> -->
      <!-- <policy domain="system" name="font" value="/path/to/font.ttf"/> -->
      <!-- <policy domain="system" name="pixel-cache-memory" value="anonymous"/> -->
      <!-- <policy domain="system" name="shred" value="2"/> -->
      <!-- <policy domain="system" name="precision" value="6"/> -->
      <!-- not needed due to the need to use explicitly by mvg: -->
      <!-- <policy domain="delegate" rights="none" pattern="MVG" /> -->
      <!-- use curl -->
      <policy domain="delegate" rights="none" pattern="URL" />
      <policy domain="delegate" rights="none" pattern="HTTPS" />
      <policy domain="delegate" rights="none" pattern="HTTP" />
      <!-- in order to avoid to get image with password text -->
      <policy domain="path" rights="none" pattern="@*" />
      <!-- disable ghostscript format types -->
      <policy domain="coder" rights="none" pattern="PS" />
      <policy domain="coder" rights="none" pattern="PS2" />
      <policy domain="coder" rights="none" pattern="PS3" />
      <policy domain="coder" rights="none" pattern="EPS" />
      <!-- <policy domain="coder" rights="none" pattern="PDF" /> -->
      <policy domain="coder" rights="none" pattern="XPS" />
    </policymap>
