{{- if .Values.tika.keda.enabled -}}
{{- if not .Values.tika.hpa.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "app.fullname" . }}-tika
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "tika") | nindent 4 }}
    app.kubernetes.io/component: "tika"
  {{- with include "app.annotations.custom" (dict "context" . "component" "tika") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}-tika
  maxReplicaCount: {{ .Values.gotenberg.keda.maxReplicas }}
  minReplicaCount: {{ .Values.gotenberg.keda.minReplicas }}
  triggers:
    - type: rabbitmq
      metadata:
        protocol: http
        host: http://guest:guest@{{ include "app.fullname" . }}-rabbit:{{ .Values.rabbit.service.port.http }}
        mode: QueueLength
        value: {{ .Values.gotenberg.keda.targetQueueLength | quote }}
        queueName: {{ .Values.gotenberg.keda.queueToWatch }}
        useRegex: "true"
        operation: "sum"
        pageSize: "500"
        timeout: "30s"
{{- end }}
{{- end }}
