apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-tika-config
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "tika") | nindent 4 }}
    app.kubernetes.io/component: tika
  {{- with include "app.annotations.custom" (dict "context" . "component" "tika") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  tika-config.xml: |
    {{- .Files.Get "files/tika/tika-config.xml.tpl" | nindent 4 }}
