environment: development

# Override domain inside values.yaml + set a global domain value
#
# domain: &default-domain "xxxxx"
# global:
#   domain: *default-domain

llm:
  # model: qwen2.5:0.5b
  model: smollm2:135m
  temperature: 0
  summarize_text_chunk_size: 1000
  summarize_text_chunk_overlap: 33
  embedding_temperatur: 0
  embedding_text_chunk_size: 250
  embedding_text_chunk_overlap: 25
  llm_rerank_temperature: 0
