environment: development

llm:
  model: smollm2:135m
  model_embedding: nomic-embed-text:v1.5
  # Warning ! This model is not intelligent enough to understand how tools work
  model_tool: smollm2:135m
  temperature: null
  summarize_text_chunk_size: 1000
  summarize_text_chunk_overlap: 33
  embedding_temperature: 0
  embedding_text_chunk_size: 250
  embedding_text_chunk_overlap: 25
  llm_rerank_temperature: 0

ingress: &default-ingress-config
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure

globalHttpRedirect:
  enabled: false

api:
  ingress: *default-ingress-config

frontend:
  ingress: *default-ingress-config
  # The dev-Server needs a bit more resources
  resources:
    requests:
      cpu: "0.1"
      memory: "1Gi"
    limits:
      cpu: "0.5"
      memory: "1.5Gi"


worker:
  # yamllint disable rule:indentation
  command: [
    "python", "-Xfrozen_modules=off",
    "-m", "debugpy",
      "--listen", "127.0.0.1:5500",
    "-m", "watchdog.watchmedo",
      "auto-restart",
      "--verbose",
      "--recursive",
      "--signal", "SIGTERM",
      "--patterns", "*.py",
      "--directory", "/code/common",
      "--directory", "/code/worker",
      "--debounce-interval", "3",
    "--",
    "python", "-Xfrozen_modules=off",
    "main.py",
      "worker",
      "--loglevel", "DEBUG"
  ]
  # yamllint enable rule:indentation
  hpa:
    enabled: false

reaper:
  # yamllint disable rule:indentation
  command: [
    "python", "-Xfrozen_modules=off",
    "-m", "debugpy",
      "--listen", "127.0.0.1:5501",
    "-m", "watchdog.watchmedo",
      "auto-restart",
      "--verbose",
      "--recursive",
      "--signal", "SIGTERM",
      "--patterns", "*.py",
      "--directory", "/code/common",
      "--directory", "/code/worker",
      "--debounce-interval", "3",
    "--",
    "python", "-Xfrozen_modules=off",
    "main.py",
      "worker",
      "--loglevel", "DEBUG"
  ]
  # yamllint enable rule:indentation
  hpa:
    enabled: false

beat:
  # yamllint disable rule:indentation
  command: [
    "python", "-Xfrozen_modules=off",
    "-m", "debugpy",
      "--listen", "127.0.0.1:5503",
    "-m", "watchdog.watchmedo",
      "auto-restart",
      "--verbose",
      "--recursive",
      "--signal", "SIGTERM",
      "--patterns", "*.py",
      "--directory", "/code/common",
      "--directory", "/code/worker",
      "--debounce-interval", "3",
    "--",
    "python", "-Xfrozen_modules=off",
    "main.py",
      "beat",
      "--loglevel", "DEBUG"
  ]
  # yamllint enable rule:indentation


flower:
  ingress: *default-ingress-config

elasticsearch:
  ingress: *default-ingress-config
  resources:
    requests:
      cpu: "0.5"
      memory: "2Gi"
    limits:
      cpu: "8"
      memory: "4Gi"

elasticvue:
  ingress: *default-ingress-config

grafana:
  ingress: *default-ingress-config

translate:
  ingress: *default-ingress-config
  hpa:
    enabled: false

minio:
  ingress: *default-ingress-config
  consoleIngress: *default-ingress-config

mongodb:
  ingress:
    enabled: true
  express:
    ingress: *default-ingress-config

rabbit:
  ingress:
    http: *default-ingress-config
    amqp:
      enabled: true

ollama:
  hpa:
    enabled: false
  pvc:
    enabled: false
  ingress: *default-ingress-config

open_webui:
  env:
    ENV: "dev"
  ingress: *default-ingress-config

dovecot:
  ingress:
    imap:
      enabled: true

roundcube:
  ingress: *default-ingress-config

prometheus:
  ingress: *default-ingress-config

redis:
  ingress:
    enabled: true
  insight:
    ingress: *default-ingress-config

rspamd:
  worker:
    ingress: *default-ingress-config
  controller:
    ingress: *default-ingress-config

tika:
  hpa:
    enabled: false
  ingress: *default-ingress-config
