translate:
  env:
    ARGOS_DEVICE_TYPE: "cuda"
  resources:
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1

ollama:
  resources:
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1
      cpu: "2"
      memory: "5Gi"
