import noTagArticle from "../../../integrationtest/assets/auto_tag_files/no_tag.txt?raw";
import basicEmail from "../../../integrationtest/assets/basic_email.eml?raw";
import attachmentEmail from "../../../integrationtest/assets/email_with_pdf_attachment.eml?raw";
import emptyFile from "../../../integrationtest/assets/empty_file.txt?raw";
import homePdfUrl from "../../../integrationtest/assets/home.pdf?url";
import networkSecurity from "../../../integrationtest/assets/knn1.txt?raw";
import accessibleDocumentUrl from "../../../integrationtest/assets/sample3.docx?url";
import testArchiveUrl from "../../../integrationtest/assets/testarchive_larger.zip?url";
import germanText from "../../../integrationtest/assets/text_de.txt?raw";

import basicEmailThumbnailUrl from "./previews/basic-email-thumbnail.png?url";
import basicEmailPdfUrl from "./previews/basic-email.pdf?url";
import basicEmailImageUrl from "./previews/basic-email.png?url";
import networkSecurityThumbnailUrl from "./previews/network-security-thumbnail.png?url";
import networkSecurityPdfUrl from "./previews/network-security.pdf?url";
import sample3Image1ThumbnailUrl from "./previews/sample3-image1-thumbnail.png?url";
import sample3Image1Url from "./previews/sample3-image1.gif?url";
import sample3Image2ThumbnailUrl from "./previews/sample3-image2-thumbnail.png?url";
import sample3Image2Url from "./previews/sample3-image2.png?url";
import sample3ThumbnailUrl from "./previews/sample3-thumbnail.png?url";
import sample3PdfUrl from "./previews/sample3.pdf?url";
import type { DemoDocument } from "./repository";

export const INITIAL_ARCHIVE_ID = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
export const ATTACHMENT_EMAIL_ID = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaab";
export const PDF_ATTACHMENT_ID = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
export const SAMPLE3_IMAGE1_ID = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
export const SAMPLE3_IMAGE2_ID = "dddddddd-dddd-4ddd-8ddd-dddddddddddd";

export const createDemoDocuments = (): DemoDocument[] => {
    const now = new Date().toISOString();
    return [
        {
            id: "11111111-1111-4111-8111-111111111111",
            name: "John Smith - Network Security.txt",
            path: "/Research/Security/John Smith - Network Security.txt",
            extension: ".txt",
            mimeType: "text/plain",
            size: 377,
            uploadedAt: now,
            createdAt: "2025-03-14T09:30:00Z",
            modifiedAt: now,
            state: "processed",
            tags: ["networking", "security"],
            content: networkSecurity,
            summary:
                "An overview of network-security controls that protect the confidentiality, integrity, and availability of data.",
            flagged: false,
            hidden: false,
            seen: false,
            language: "en",
            authors: ["Jon Smith"],
            secrets: [],
            source: "api-upload",
            archiveIds: [INITIAL_ARCHIVE_ID],
            data: networkSecurity,
            translations: [],
            thumbnail: { url: networkSecurityThumbnailUrl, totalFrames: 1 },
            rendered: { officePdfUrl: networkSecurityPdfUrl },
        },
        {
            id: "22222222-2222-4222-8222-222222222222",
            name: "basic_email.eml",
            path: "/Mail/Inbox/basic_email.eml",
            extension: ".eml",
            mimeType: "message/rfc822",
            size: 1_519,
            uploadedAt: "2020-05-05T09:06:05Z",
            createdAt: "2008-11-22T04:04:59Z",
            modifiedAt: now,
            state: "processed",
            tags: ["email", "interesting"],
            content:
                "From: Mikel Lindsaar <test@lindsaar.net>\nSubject: Testing 123\n\nPlain email. Hope it works well!\n\nMikel",
            summary:
                "A short test email from Mikel Lindsaar confirming that plain-email delivery works.",
            flagged: false,
            hidden: false,
            seen: true,
            language: "en",
            authors: ["Mikel Lindsaar", "test@lindsaar.net"],
            secrets: [],
            source: "imap",
            isSpam: true,
            attachmentsSkipped: true,
            translations: [],
            archiveIds: [INITIAL_ARCHIVE_ID],
            data: basicEmail,
            thumbnail: { url: basicEmailThumbnailUrl, totalFrames: 1 },
            rendered: {
                imageUrl: basicEmailImageUrl,
                officePdfUrl: basicEmailPdfUrl,
            },
        },
        {
            id: ATTACHMENT_EMAIL_ID,
            name: "email_with_pdf_attachment.eml",
            path: "/Mail/Inbox/email_with_pdf_attachment.eml",
            extension: ".eml",
            mimeType: "message/rfc822",
            size: 2_973,
            uploadedAt: "2025-02-10T13:00:00Z",
            createdAt: "2016-06-01T16:35:07Z",
            modifiedAt: "2016-06-01T16:35:07Z",
            state: "processed",
            tags: ["attachment", "email", "🤖 interesting"],
            content:
                "This email contains a PDF attachment that can be rendered in Loom.",
            summary:
                "A multipart sample email containing a renderable PDF attachment.",
            flagged: false,
            hidden: false,
            seen: true,
            language: "en",
            authors: ["Demo Sender", "sender@example.com"],
            secrets: [],
            source: "api-upload",
            attachments: [{ id: PDF_ATTACHMENT_ID, name: "home.pdf" }],
            translations: [],
            archiveIds: [],
            data: attachmentEmail,
        },
        {
            id: PDF_ATTACHMENT_ID,
            name: "home.pdf",
            path: "/Mail/Inbox/email_with_pdf_attachment.eml/home.pdf",
            extension: ".pdf",
            mimeType: "application/pdf",
            size: 1_737,
            uploadedAt: "2025-02-10T13:00:00Z",
            createdAt: "2016-06-01T16:35:07Z",
            modifiedAt: "2016-06-01T16:35:07Z",
            state: "processed",
            tags: ["pdf"],
            content: "A one-page PDF generated with Matplotlib.",
            summary: "A small renderable PDF attached to the sample email.",
            flagged: false,
            hidden: false,
            seen: true,
            language: "en",
            authors: [],
            secrets: [],
            source: "api-upload",
            parentId: ATTACHMENT_EMAIL_ID,
            translations: [],
            archiveIds: [],
            data: "Binary PDF fixture bundled with the demo.",
            downloadUrl: homePdfUrl,
            rendered: { officePdfUrl: homePdfUrl },
        },
        {
            id: "44444444-4444-4444-8444-444444444444",
            name: "sample3.docx",
            path: "/Documents/Accessibility/sample3.docx",
            extension: ".docx",
            mimeType:
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            size: 34_375,
            uploadedAt: "2025-02-12T16:03:00Z",
            createdAt: "2016-12-06T21:20:00Z",
            modifiedAt: "2016-12-06T22:10:00Z",
            state: "processed",
            tags: ["accessibility", "office", "🤖 sample"],
            content:
                "Sample Document. This document demonstrates accessible headings, lists, links, images, tables, and columns for assistive technologies such as screen readers.",
            summary:
                "An accessible Word sample covering structured headings, lists, links, image alt text, tables, and columns.",
            flagged: false,
            hidden: false,
            seen: true,
            language: "en",
            authors: ["Mike Scott"],
            secrets: [],
            source: "api-upload",
            featured: true,
            translations: [],
            archiveIds: [],
            data: "Binary DOCX fixture bundled with the demo.",
            downloadUrl: accessibleDocumentUrl,
            thumbnail: { url: sample3ThumbnailUrl, totalFrames: 1 },
            rendered: { officePdfUrl: sample3PdfUrl },
            attachments: [
                { id: SAMPLE3_IMAGE1_ID, name: "image1.gif" },
                { id: SAMPLE3_IMAGE2_ID, name: "image2.png" },
            ],
        },
        {
            id: SAMPLE3_IMAGE1_ID,
            name: "image1.gif",
            path: "/Documents/Accessibility/sample3.docx/image1.gif",
            extension: ".gif",
            mimeType: "image/gif",
            size: 23_722,
            uploadedAt: "2025-02-12T16:03:00Z",
            createdAt: "2016-12-06T21:20:00Z",
            modifiedAt: "2016-12-06T21:20:00Z",
            state: "processed",
            tags: ["accessibility", "office"],
            content: "",
            summary:
                "An image embedded in the sample3.docx accessibility document.",
            imageDescription:
                "A decorative graphic embedded in the accessible Word document sample.",
            flagged: false,
            hidden: false,
            seen: true,
            language: "unknown",
            authors: [],
            secrets: [],
            source: "api-upload",
            parentId: "44444444-4444-4444-8444-444444444444",
            translations: [],
            archiveIds: [],
            data: "Binary GIF fixture bundled with the demo.",
            downloadUrl: sample3Image1Url,
            thumbnail: { url: sample3Image1ThumbnailUrl, totalFrames: 1 },
            rendered: { imageUrl: sample3Image1Url },
        },
        {
            id: SAMPLE3_IMAGE2_ID,
            name: "image2.png",
            path: "/Documents/Accessibility/sample3.docx/image2.png",
            extension: ".png",
            mimeType: "image/png",
            size: 14_317,
            uploadedAt: "2025-02-12T16:03:00Z",
            createdAt: "2016-12-06T21:20:00Z",
            modifiedAt: "2016-12-06T21:20:00Z",
            state: "processed",
            tags: ["accessibility", "office"],
            content: "",
            summary:
                "An image embedded in the sample3.docx accessibility document.",
            imageDescription:
                "A screenshot or diagram embedded in the accessible Word document sample.",
            flagged: false,
            hidden: false,
            seen: true,
            language: "unknown",
            authors: [],
            secrets: [],
            source: "api-upload",
            parentId: "44444444-4444-4444-8444-444444444444",
            translations: [],
            archiveIds: [],
            data: "Binary PNG fixture bundled with the demo.",
            downloadUrl: sample3Image2Url,
            thumbnail: { url: sample3Image2ThumbnailUrl, totalFrames: 1 },
            rendered: { imageUrl: sample3Image2Url },
        },
        {
            id: "55555555-5555-4555-8555-555555555555",
            name: "testarchive_larger.zip",
            path: "/Crawler/Imports/testarchive_larger.zip",
            extension: ".zip",
            mimeType: "application/zip",
            size: 13_839,
            uploadedAt: "2023-07-11T10:49:00Z",
            createdAt: "2022-09-27T14:22:00Z",
            modifiedAt: "2023-07-11T10:49:00Z",
            state: "processing",
            tags: ["archive", "crawler"],
            content:
                "Archive containing a PDF, a TeX source file, an image, two text files, and an empty ignore file in nested folders.",
            summary:
                "A nested integration-test archive used to demonstrate extracted document trees and mixed file types.",
            flagged: false,
            hidden: false,
            seen: false,
            language: "en",
            authors: [],
            secrets: [],
            source: "crawlerX",
            translations: [],
            archiveIds: [],
            data: "Binary ZIP fixture bundled with the demo.",
            downloadUrl: testArchiveUrl,
        },
        {
            id: "66666666-6666-4666-8666-666666666666",
            name: "text_de.txt",
            path: "/Documents/Translations/text_de.txt",
            extension: ".txt",
            mimeType: "text/plain",
            size: 233,
            uploadedAt: "2025-01-20T13:20:00Z",
            createdAt: "2025-01-20T13:18:00Z",
            modifiedAt: "2025-01-20T13:18:00Z",
            state: "processed",
            tags: ["german", "translation"],
            content: germanText,
            summary:
                "Kurzer deutscher Beispieltext zum Testen der Spracherkennung und Übersetzung.",
            flagged: false,
            hidden: false,
            seen: true,
            language: "de",
            authors: [],
            secrets: [],
            source: "api-upload",
            translations: [
                {
                    confidence: 100,
                    language: "de",
                    text: "This is a German text. It was written in the German language and contains German words and structure.\nI am now writing a few more words here, but only to test the translation engine a little better.",
                },
            ],
            archiveIds: [],
            data: germanText,
        },
        {
            id: "77777777-7777-4777-8777-777777777777",
            name: "no_tag.txt",
            path: "/News/Samples/no_tag.txt",
            extension: ".txt",
            mimeType: "text/plain",
            size: 1_149,
            uploadedAt: "2025-04-24T07:00:00Z",
            createdAt: "2025-04-24T06:30:00Z",
            modifiedAt: "2025-04-24T06:30:00Z",
            state: "processed",
            tags: ["news", "sample", "🤖 interesting"],
            content: noTagArticle,
            summary:
                "A satirical news story about classifying pizza as a vegetable through belief.",
            flagged: false,
            hidden: false,
            seen: false,
            language: "en",
            authors: ["Institute for Culinary Anomalies"],
            secrets: [],
            source: "crawler-news",
            contentTruncated: true,
            translations: [],
            archiveIds: [INITIAL_ARCHIVE_ID],
            data: noTagArticle,
        },
        {
            id: "88888888-8888-4888-8888-888888888888",
            name: "test.env",
            path: "/Security/Quarantine/test.env",
            extension: ".env",
            mimeType: "text/plain",
            size: 680,
            uploadedAt: "2025-05-03T12:40:00Z",
            createdAt: "2025-05-03T12:39:00Z",
            modifiedAt: "2025-05-03T12:39:00Z",
            state: "processed",
            tags: ["quarantine", "secrets"],
            content:
                "# Redacted security-scanner fixture\nDB_PASSWORD=[REDACTED]\nAPP_SECRET_KEY=[REDACTED]\nSLACK_WEBHOOK_URL=[REDACTED]",
            summary:
                "A redacted environment file with representative database, application-key, and webhook findings.",
            flagged: true,
            hidden: false,
            seen: false,
            language: "en",
            authors: [],
            secrets: ["database-password", "generic-api-key", "slack-webhook"],
            source: "api-upload",
            translations: [],
            archiveIds: [],
            data: "# Redacted demo fixture\nAll credential values were removed from the published demo.\n",
        },
        {
            id: "99999999-9999-4999-8999-999999999999",
            name: "test_installer.msi",
            path: "/Failed Imports/test_installer.msi",
            extension: ".msi",
            mimeType: "application/x-msi",
            size: 2_572_288,
            uploadedAt: "2025-05-04T17:05:00Z",
            createdAt: "2025-05-04T17:04:00Z",
            modifiedAt: "2025-05-04T17:04:00Z",
            state: "failed",
            tags: ["installer", "quarantine"],
            content:
                "The executable integration fixture is represented by metadata only and was intentionally omitted from the public demo bundle.",
            summary:
                "A 2.57 MB installer fixture whose failed ingestion demonstrates size and processing-state filters.",
            flagged: true,
            hidden: false,
            seen: false,
            language: "en",
            authors: [],
            secrets: [],
            source: "api-upload",
            translations: [],
            archiveIds: [],
            data: "The test installer binary is intentionally omitted from the public demo.\n",
        },
        {
            id: "00000000-0000-4000-8000-000000000000",
            name: "empty_file.txt",
            path: "/Hidden/empty_file.txt",
            extension: ".txt",
            mimeType: "text/plain",
            size: 0,
            uploadedAt: "2025-05-06T10:00:00Z",
            createdAt: "2025-05-06T10:00:00Z",
            modifiedAt: "2025-05-06T10:00:00Z",
            state: "processed",
            tags: ["empty"],
            content: emptyFile,
            summary:
                "An empty integration-test file hidden from normal results.",
            flagged: false,
            hidden: true,
            seen: true,
            language: "unknown",
            authors: [],
            secrets: [],
            source: "api-upload",
            translations: [],
            archiveIds: [],
            data: emptyFile,
        },
    ];
};
