# The mouse, on a console that has no idea what one is.
#
# The appliance has no display server -- no X, no Wayland, no compositor -- and
# tty1 is the whole user interface (console.nix). A Linux VT has no mouse driver
# behind it, so nothing about pointing and clicking is free here. What this
# module lands is the half that runs as a daemon; the half that turns events
# into something tmux understands is `loom-console-mouse`, wired into the
# session by console.nix.
#
# Three facts decide the shape of all of it, and each is read out of source
# rather than assumed:
#
#   * console_codes(4): mouse reports reach a console's input stream "only when
#     the virtual terminal driver receives a mouse update ioctl", and "these
#     ioctls must be generated by a mouse-aware user-mode application such as
#     the gpm(8) daemon". An intermediate program is the mechanism, not a
#     design choice.
#
#   * gpm is NOT that intermediate program, despite the sentence above naming
#     it. Its whole on-screen behaviour is src/daemon/do_selection.c, which only
#     ever calls selection_copy() with sel_mode 3 (highlight the pointer) or
#     event->clicks (0/1/2 -- char, word, line). Nothing in the tree references
#     TIOCL_SELMOUSEREPORT. So "gpm plus `set -g mouse on`" produces a pointer
#     and zero tmux events, silently. That is what loom-console-mouse is for.
#
#   * What gpm IS good for is everything below that: decoding a mouse, tracking
#     an absolute position across the console, acceleration, clamping, the
#     wheel, and drawing the pointer. Writing that again to avoid one daemon
#     would be a bad trade.
#
# So gpm runs, draws the pointer, and serves events on /dev/gpmctl. It does not
# talk to tmux and is not expected to.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.loom.consoleMouse;

  # The shim console.nix runs the tmux client under. Pure stdlib -- pty,
  # termios, fcntl, struct, select, socket -- so there is nothing to put on its
  # PATH and no dependency beyond the python3 that nixos/usb-ingest already
  # pulls into this closure.
  #
  # The unit tests cover the three things that are wrong in a way nobody would
  # notice from a screenshot: the gpm wire format (a struct one byte out yields
  # plausible-looking nonsense rather than an error), the button bookkeeping
  # gpm's press/release asymmetry forces, and the ordering that keeps the
  # kernel's cached pointer cell honest. Running them at build time means a
  # mistake there fails `nix-build` in seconds instead of on a console in the
  # field.
  loom-console-mouse = pkgs.python3Packages.buildPythonApplication {
    pname = "loom-console-mouse";
    version = "0.1.0";
    src = ./console-mouse;
    pyproject = true;

    build-system = [ pkgs.python3Packages.setuptools ];
    nativeCheckInputs = [ pkgs.python3Packages.pytest ];

    checkPhase = ''
      runHook preCheck
      PYTHONPATH=$PWD pytest tests -q
      runHook postCheck
    '';

    meta.mainProgram = "loom-console-mouse";
  };
in
{
  options.loom.consoleMouse = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Whether the appliance runs the console mouse daemon.

        An option rather than an unconditional import so that the wiring is
        greppable from one place, and so a box that turns out to misbehave
        with gpm running can be built without it.

        It deliberately does NOT gate the shim below. `loom-console` wraps the
        tmux client either way, and the shim `exec`s straight through when it
        cannot reach gpm -- so switching this off leaves exactly the
        keyboard-only session console.nix shipped before, by the same code
        path that already has to work when no mouse is plugged in. One path
        that is always exercised beats a second one that is not.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      internal = true;
      readOnly = true;
      description = ''
        `loom-console-mouse`: the pty shim that sits between tty1 and the tmux
        client, turning gpm events into SGR mouse reports.

        An option rather than a literal in console.nix for the same reason
        `loom.branding.eyes` is one -- the thing is defined beside the daemon
        it talks to, and console.nix names it once.
      '';
    };
  };

  config = lib.mkMerge [
    {
      loom.consoleMouse.package = loom-console-mouse;
    }

    (lib.mkIf cfg.enable {
      # -------------------------------------------------------------------------
      # /dev/input/mice has to exist before gpm can open it.
      #
      # CONFIG_INPUT_MOUSEDEV is `m` on the NixOS kernel, and the unit below is
      # Requires=dev-input-mice.device -- so on a box where nothing else happens
      # to pull the module in, the device never appears, the unit never starts,
      # and the only trace is a job sitting in `systemctl list-jobs`. Naming it
      # here is one line against a failure mode that reads as "the mouse just does
      # not work".
      #
      # And it is mousedev rather than a specific /dev/input/eventN on purpose.
      # mousedev multiplexes every mouse on the box into one character device, so
      # a mouse plugged in after boot -- the normal case for an appliance that
      # gets handed over with no peripherals -- is picked up with no hotplug rule
      # and no restart. An evdev node is bound to one device and would need both.
      # -------------------------------------------------------------------------
      boot.kernelModules = [ "mousedev" ];

      # -------------------------------------------------------------------------
      # gpm
      #
      # Written out here rather than `services.gpm.enable = true`, for two reasons
      # that the stock module cannot express:
      #
      #   * It hardcodes `-t ${cfg.protocol}` with a default of `ps/2`, and the
      #     option is the only thing it exposes. ps/2 has no wheel. imps2 is the
      #     same protocol plus the scroll wheel, which is how a pane gets
      #     scrolled, so it is not optional here.
      #   * It has no `after`, and the ordering below is the whole reason this
      #     unit is worth writing by hand.
      # -------------------------------------------------------------------------
      systemd.services.gpm = {
        description = "Console pointer and mouse event decoder";
        wantedBy = [ "multi-user.target" ];
        requires = [ "dev-input-mice.device" ];

        # After the font, and this is not a nicety.
        #
        # gpm measures the console once, in get_console_size() at startup, and
        # re-reads it only on SIGWINCH (src/daemon/old_main.c:140). SIGWINCH is
        # delivered to a tty's foreground process group, and a daemon is never in
        # one -- so in practice that re-read never happens by itself.
        #
        # Meanwhile branding.nix documents, at length, that this console is
        # resized four times during boot: fbcon's built-in font, then Cozette,
        # then the DRM driver taking over and resetting it, then Cozette again.
        # A gpm that started before the last of those has clamped its pointer to a
        # grid that no longer exists -- on the 2560x1600 panel the appliance was
        # tested on that is the difference between 160x50 and 426x123, so roughly
        # two thirds of the screen becomes unreachable with the mouse.
        #
        # loom-console-font.service is After=plymouth-quit-wait.service, which is
        # what makes it late enough to be on the far side of the reset in run
        # mode. Ordering against it inherits that.
        after = [
          "dev-input-mice.device"
          "loom-console-font.service"
        ];

        serviceConfig = {
          Type = "forking";
          PIDFile = "/run/gpm.pid";
          # The leading `@` sets argv[0] separately from the executable, which is
          # what the stock NixOS module does as well: gpm re-execs itself by
          # argv[0] when it backgrounds.
          #
          # No -R: repeater mode writes decoded packets to /dev/gpmdata for a
          # second consumer, and there is none. loom-console-mouse is an ordinary
          # client on /dev/gpmctl.
          ExecStart = "@${pkgs.gpm}/sbin/gpm gpm -m /dev/input/mice -t imps2";
        };
      };

      # -------------------------------------------------------------------------
      # The resize the ordering above cannot catch.
      #
      # loom-console-font-reapply is started from a udev rule when a DRM card
      # appears, which is asynchronous and can land after gpm is already running
      # -- that is the entire reason branding.nix has a second font unit at all.
      # Every pass of it resizes every VT, so gpm has to pick the new size up
      # somehow.
      #
      # RESTARTED rather than signalled, and this is not a stylistic choice.
      # gpm handles SIGWINCH -- `gpm_killed()` sets `opt_resize`, and the main
      # loop then calls `get_console_size()` and walks its client table to pass
      # the signal on -- but that path SEGFAULTS. Measured, in the VM test: gpm
      # logs "gpm pid N is resizing :-)" and dies in `old_main` a moment later.
      #
      # Which makes sense once you see why: SIGWINCH is delivered to a tty's
      # foreground process group, and gpm is a daemon that is never in one, so
      # nothing sends it that signal in ordinary use. The resize path is
      # effectively dead code upstream, and dead code rots. The same fact that
      # makes the re-read necessary here is the one that kept the bug hidden.
      #
      # A restart re-reads the console size the way every other gpm start does,
      # on a path that is exercised on every boot. It costs a reconnect for any
      # client -- `loom-console-mouse` retries, so the mouse comes back on its
      # own -- and in practice there is no client yet: this fires during udev
      # coldplug, long before anybody has pressed a key to open a session.
      #
      # `try-restart` so a box with gpm switched off is not handed a unit to
      # start; `--no-block` because waiting on a job from inside a unit means
      # blocking on the queue this unit is itself in (box.nix makes the same
      # point about restarting a getty); and `-` so that a failure here costs the
      # pointer and never the font, which is every screen on the box.
      #
      # This extends a unit branding.nix owns, which is safe because
      # nixos/default.nix's `applianceModules` always carries both -- and if it
      # ever did not, the module system would produce a unit with an
      # ExecStartPost and no ExecStart rather than something subtly wrong.
      # -------------------------------------------------------------------------
      systemd.services.loom-console-font-reapply.serviceConfig.ExecStartPost = [
        "-${config.systemd.package}/bin/systemctl try-restart --no-block gpm.service"
      ];
    })
  ];
}
