# The appliance network.
#
# In run mode the box is an island: it owns its subnet, hands out addresses, and
# resolves every `*.loom` name to itself. A visitor plugs a laptop into the
# ethernet port and https://frontend.loom works with no configuration on their
# side -- which is the main way Loom is used on these boxes.
#
# In setup mode it is an ordinary DHCP client, because the box needs real
# internet exactly once: to populate minikube's image store.
{
  config,
  lib,
  pkgs,
  loomSubnet,
  loomInterface,
  ...
}:
let
  boxAddress = "${loomSubnet}.1";
  poolStart = "${loomSubnet}.100";
  poolEnd = "${loomSubnet}.200";
  isRun = config.loom.mode == "run";
in
{
  config = lib.mkMerge [
    # -------------------------------------------------------------------------
    # Run mode: static address, DHCP server, wildcard DNS.
    # -------------------------------------------------------------------------
    (lib.mkIf isRun {
      networking.useDHCP = false;
      networking.interfaces.${loomInterface}.ipv4.addresses = [
        {
          address = boxAddress;
          prefixLength = 24;
        }
      ];

      # No upstream resolver: there is nothing upstream. Pointing at one would
      # only add a timeout to every lookup that is not ours.
      networking.nameservers = [ "127.0.0.1" ];

      services.dnsmasq = {
        enable = true;
        resolveLocalQueries = false;
        settings = {
          interface = loomInterface;
          # Refuse to answer on anything but our own link, so the box can never
          # act as a rogue DHCP server if it is cabled into a real network.
          bind-interfaces = true;

          dhcp-range = "${poolStart},${poolEnd},255.255.255.0,12h";
          dhcp-option = [
            # Deliberately no option:router -- the box is not a gateway and
            # advertising it as one would black-hole the client's traffic.
            "option:dns-server,${boxAddress}"
          ];

          # Wildcard, so this covers every name under .loom rather than just
          # the 22 currently in vars.sh.
          address = "/loom/${boxAddress}";

          no-resolv = true;
          no-hosts = true;
          domain-needed = true;
          bogus-priv = true;
          log-dhcp = true;
        };
      };

      networking.firewall = {
        allowedTCPPorts = [ 53 ];
        allowedUDPPorts = [
          53
          67 # DHCP server
        ];
      };

      # A record of the generated subnet, for whoever debugs the box later
      # without access to the machine that built the stick.
      environment.etc."loom/network.conf".text = ''
        # Generated by build-appliance-image. Informational only -- the live
        # values come from the NixOS configuration, not from this file.
        LOOM_INTERFACE=${loomInterface}
        LOOM_SUBNET=${loomSubnet}.0/24
        LOOM_BOX_ADDRESS=${boxAddress}
        LOOM_DHCP_POOL=${poolStart}-${poolEnd}
      '';
    })

    # -------------------------------------------------------------------------
    # Setup mode: ordinary client, so skaffold can reach the registries.
    # -------------------------------------------------------------------------
    (lib.mkIf (!isRun) {
      networking.useDHCP = lib.mkForce true;
      services.dnsmasq.enable = false;
    })

    # -------------------------------------------------------------------------
    # Radios off in both modes.
    #
    # Software disable, module blacklist and an rfkill block. A firmware-level
    # disable in the Spark's BIOS is the only true guarantee and is a documented
    # manual step -- see Documentation/appliance.md.
    # -------------------------------------------------------------------------
    {
      networking.wireless.enable = false;
      networking.networkmanager.enable = false;
      hardware.bluetooth.enable = false;

      boot.blacklistedKernelModules = [
        "bluetooth"
        "btusb"
        "btintel"
        "btbcm"
        "btrtl"
        "cfg80211"
        "mac80211"
      ];

      systemd.services.loom-rfkill-block = {
        description = "Hard-block all radios";
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          # `rfkill block all` exits non-zero when there is nothing to block,
          # which on a box with the modules blacklisted is the expected case.
          ExecStart = "${pkgs.util-linux}/bin/rfkill block all";
          SuccessExitStatus = [
            0
            1
          ];
        };
      };
    }
  ];
}
