# The appliance network.
#
# In run mode the box is an island: it owns its subnet, hands out addresses, and
# resolves every `*.loom` name to itself. A visitor plugs a laptop into the
# ethernet port and https://frontend.loom works with no configuration on their
# side -- which is the main way Loom is used on these boxes.
#
# In setup mode it is an ordinary DHCP client, because the box needs real
# internet exactly once: to populate minikube's image store.
{
  config,
  lib,
  pkgs,
  loomSubnet,
  loomInterface,
  ...
}:
let
  boxAddress = "${loomSubnet}.1";
  poolStart = "${loomSubnet}.100";
  poolEnd = "${loomSubnet}.200";
  isRun = config.loom.mode == "run";

  # The appliance never refers to a kernel-assigned interface name. Predictable
  # naming gives `enp1s0f0np0` on the Spark and `enp*` on the EVO-X2, neither of
  # which a single image could hardcode -- and a wrong guess boots a box with a
  # static address on an interface that does not exist, no DHCP, no DNS, and no
  # sshd to fix it from. So udev renames the platform's NIC to a fixed name and
  # everything below pins to that.
  applianceInterface = "loom0";

  # `loomInterface` is the escape hatch: empty means "use the platform's match".
  netMatch =
    if loomInterface != "" then { OriginalName = loomInterface; } else config.loom.platform.netMatch;
in
{
  config = lib.mkMerge [
    # -------------------------------------------------------------------------
    # Run mode: static address, DHCP server, wildcard DNS.
    # -------------------------------------------------------------------------
    (lib.mkIf isRun {
      networking.useDHCP = false;
      networking.interfaces.${applianceInterface}.ipv4.addresses = [
        {
          address = boxAddress;
          prefixLength = 24;
        }
      ];

      # No upstream resolver: there is nothing upstream. Pointing at one would
      # only add a timeout to every lookup that is not ours.
      networking.nameservers = [ "127.0.0.1" ];

      services.dnsmasq = {
        enable = true;
        resolveLocalQueries = false;
        settings = {
          interface = applianceInterface;
          # Refuse to answer on anything but our own link, so the box can never
          # act as a rogue DHCP server if it is cabled into a real network.
          bind-interfaces = true;

          dhcp-range = "${poolStart},${poolEnd},255.255.255.0,12h";
          dhcp-option = [
            # Deliberately no option:router -- the box is not a gateway and
            # advertising it as one would black-hole the client's traffic.
            "option:dns-server,${boxAddress}"
          ];

          # Wildcard, so this covers every name under .loom rather than just
          # the 22 currently in vars.sh.
          address = "/loom/${boxAddress}";

          no-resolv = true;
          no-hosts = true;
          domain-needed = true;
          bogus-priv = true;
          log-dhcp = true;
        };
      };

      networking.firewall = {
        allowedTCPPorts = [ 53 ];
        allowedUDPPorts = [
          53
          67 # DHCP server
        ];
      };

      # A record of the generated subnet, for whoever debugs the box later
      # without access to the machine that built the stick.
      environment.etc."loom/network.conf".text = ''
        # Generated by build-appliance-image. Informational only -- the live
        # values come from the NixOS configuration, not from this file.
        LOOM_INTERFACE=${applianceInterface}
        LOOM_SUBNET=${loomSubnet}.0/24
        LOOM_BOX_ADDRESS=${boxAddress}
        LOOM_DHCP_POOL=${poolStart}-${poolEnd}
      '';
    })

    # -------------------------------------------------------------------------
    # Setup mode: ordinary client, so skaffold can reach the registries.
    # -------------------------------------------------------------------------
    (lib.mkIf (!isRun) {
      networking.useDHCP = lib.mkForce true;
      services.dnsmasq.enable = false;
    })

    # -------------------------------------------------------------------------
    # A stable name for the appliance NIC, in both modes.
    #
    # .link files are applied by udev whether or not systemd-networkd is running
    # (nixpkgs says so in networkd.nix, right above the option), so this works
    # alongside the scripted/dhcpcd networking the appliance actually uses.
    # -------------------------------------------------------------------------
    {
      systemd.network.links."10-${applianceInterface}" = {
        matchConfig = netMatch;
        linkConfig.Name = applianceInterface;
      };

      # If the match is wrong, everything above silently does nothing and the box
      # comes up unreachable -- with no sshd, the console is the only way to find
      # out why. Say so there, loudly, rather than leaving someone to guess.
      systemd.services.loom-network-check = {
        description = "Warn when the appliance interface is missing";
        wantedBy = [ "multi-user.target" ];
        after = [ "systemd-udev-settle.service" ];
        before = [ "loom.service" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          StandardOutput = "journal+console";
          StandardError = "journal+console";
        };
        # Never fails: this is a diagnostic, and blocking the boot of an
        # appliance whose only interface is missing helps nobody.
        script = ''
          if [ -e /sys/class/net/${applianceInterface} ]; then
            exit 0
          fi
          echo "[!] ${applianceInterface} does not exist -- no address, no DHCP, no *.loom."
          echo "[!] The platform's interface match did not select anything. Present instead:"
          for candidate in /sys/class/net/*; do
            name="$(basename "$candidate")"
            [ "$name" = lo ] && continue
            echo "[!]   $name"
          done
          echo "[!] Rebuild the image with --interface <name> to pin one of the above."
          exit 0
        '';
      };
    }

    # -------------------------------------------------------------------------
    # Radios off in both modes.
    #
    # Software disable, module blacklist and an rfkill block. Generic on purpose
    # -- this covers the Spark's radios and the EVO-X2's MediaTek Wi-Fi/BT alike.
    # A firmware-level disable in the box's own BIOS is the only true guarantee
    # and is a documented manual step -- see Documentation/appliance.md.
    # -------------------------------------------------------------------------
    {
      networking.wireless.enable = false;
      networking.networkmanager.enable = false;
      hardware.bluetooth.enable = false;

      boot.blacklistedKernelModules = [
        "bluetooth"
        "btusb"
        "btintel"
        "btbcm"
        "btrtl"
        "cfg80211"
        "mac80211"
      ];

      systemd.services.loom-rfkill-block = {
        description = "Hard-block all radios";
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          # `rfkill block all` exits non-zero when there is nothing to block,
          # which on a box with the modules blacklisted is the expected case.
          ExecStart = "${pkgs.util-linux}/bin/rfkill block all";
          SuccessExitStatus = [
            0
            1
          ];
        };
      };
    }
  ];
}
