# The appliance network.
#
# In run mode the box is an island: it owns its subnet, hands out addresses, and
# resolves every `*.loom` name to itself. A visitor plugs a laptop into the
# ethernet port and https://frontend.loom works with no configuration on their
# side -- which is the main way Loom is used on these boxes.
#
# In setup mode it is an ordinary DHCP client, because the box needs real
# internet exactly once: to populate minikube's image store.
{
  config,
  lib,
  pkgs,
  loomSubnet,
  loomInterface,
  ...
}:
let
  boxAddress = "${loomSubnet}.1";
  poolStart = "${loomSubnet}.100";
  poolEnd = "${loomSubnet}.200";
  isRun = config.loom.mode == "run";

  # The appliance never refers to a kernel-assigned interface name. Predictable
  # naming gives `enp1s0f0np0` on the Spark and `enp*` on the EVO-X2, neither of
  # which a single image could hardcode -- and a wrong guess boots a box with a
  # static address on an interface that does not exist, no DHCP, no DNS, and no
  # sshd to fix it from. So udev renames the platform's NIC to a fixed name and
  # everything below pins to that.
  applianceInterface = "loom0";

  # `loomInterface` is the escape hatch: empty means "use the platform's match".
  netMatch =
    if loomInterface != "" then { OriginalName = loomInterface; } else config.loom.platform.netMatch;

  # With the access point enabled (wifi.nix), the wired NIC stops being the thing
  # the appliance addresses and becomes one port of a bridge. Everything that
  # used to pin to `loom0` -- the static address, dnsmasq's binding, the firewall
  # -- moves onto the bridge, so that a client is on the same segment, in the same
  # pool, behind the same resolver whether it arrived over the air or over copper.
  #
  # `loom0` keeps meaning "the physical NIC" in both builds. Only the name of the
  # interface holding the address changes.
  wifiEnabled = config.loom.wifi.enable;
  bridgeInterface = config.loom.wifi.bridge;
  serviceInterface = if wifiEnabled then bridgeInterface else applianceInterface;
in
{
  config = lib.mkMerge [
    # -------------------------------------------------------------------------
    # Run mode: static address, DHCP server, wildcard DNS.
    # -------------------------------------------------------------------------
    (lib.mkIf isRun {
      networking.useDHCP = false;
      networking.interfaces.${serviceInterface}.ipv4.addresses = [
        {
          address = boxAddress;
          prefixLength = 24;
        }
      ];

      # No upstream resolver: there is nothing upstream. Pointing at one would
      # only add a timeout to every lookup that is not ours.
      networking.nameservers = [ "127.0.0.1" ];

      services.dnsmasq = {
        enable = true;
        resolveLocalQueries = false;
        settings = {
          interface = serviceInterface;
          # Refuse to answer on anything but our own link, so the box can never
          # act as a rogue DHCP server if it is cabled into a real network.
          bind-interfaces = true;

          dhcp-range = "${poolStart},${poolEnd},255.255.255.0,12h";
          dhcp-option = [
            # Deliberately no option:router -- the box is not a gateway and
            # advertising it as one would black-hole the client's traffic.
            "option:dns-server,${boxAddress}"
          ];

          # Wildcard, so this covers every name under .loom rather than just
          # the 22 currently in vars.sh.
          address = "/loom/${boxAddress}";

          no-resolv = true;
          no-hosts = true;
          domain-needed = true;
          bogus-priv = true;
          log-dhcp = true;
        };
      };

      networking.firewall = {
        allowedTCPPorts = [ 53 ];
        allowedUDPPorts = [
          53
          67 # DHCP server
        ];
      };

      # A record of the generated subnet, for whoever debugs the box later
      # without access to the machine that built the stick.
      # Deliberately carries no passphrase. This file is 0644 and the banner
      # reads it as the operator; the WPA key is interpolated into loom-info
      # from the closure instead (box.nix).
      environment.etc."loom/network.conf".text = ''
        # Generated by build-appliance-image. Informational only -- the live
        # values come from the NixOS configuration, not from this file.
        # LOOM_INTERFACE holds the address and serves DHCP; LOOM_WIRED_INTERFACE
        # is the port to plug a cable into. They differ only when the access
        # point is enabled and both are ports of a bridge.
        LOOM_INTERFACE=${serviceInterface}
        LOOM_WIRED_INTERFACE=${applianceInterface}
        LOOM_SUBNET=${loomSubnet}.0/24
        LOOM_BOX_ADDRESS=${boxAddress}
        LOOM_DHCP_POOL=${poolStart}-${poolEnd}
      ''
      + lib.optionalString wifiEnabled ''
        LOOM_WIFI_INTERFACE=${config.loom.wifi.interface}
        LOOM_WIFI_SSID=${config.loom.wifi.ssid}
      '';
    })

    # -------------------------------------------------------------------------
    # The bridge that makes wired and wireless the same network. Run mode with
    # --wifi only; wifi.nix owns the radio itself.
    # -------------------------------------------------------------------------
    (lib.mkIf (isRun && wifiEnabled) {
      # Declared with NO members, which looks wrong and is the whole point.
      #
      # The scripted bridge (nixpkgs network-interfaces-scripted.nix) sets
      # `bindsTo` on the .device unit of every interface it is told to enslave.
      # Naming loom0 here would therefore bind the bridge -- and so the address,
      # dnsmasq and every *.loom name -- to an ethernet port being present. A box
      # deployed for its access point, with nothing plugged into the wired port,
      # would come up with no address at all and no way in to find out why.
      #
      # So the bridge is created unconditionally and the ports attach to it:
      # loom0 below, and the radio by hostapd's own `bridge=` (wifi.nix).
      networking.bridges.${bridgeInterface}.interfaces = [ ];

      systemd.services.loom-bridge-attach = {
        description = "Attach the wired port to the appliance bridge";
        wantedBy = [ "network.target" ];
        after = [
          "${bridgeInterface}-netdev.service"
          "systemd-udev-settle.service"
        ];
        # Before the address, so a cabled client cannot get a DHCP lease over a
        # port that is not in the bridge yet.
        before = [ "network-addresses-${bridgeInterface}.service" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        path = [ pkgs.iproute2 ];
        # Never fails. A missing loom0 is already reported by
        # loom-network-check, and taking the boot down here would cost the
        # access point too -- the one way left into a box in that state.
        script = ''
          if [ ! -e /sys/class/net/${applianceInterface} ]; then
            echo "${applianceInterface} is not present; bridge ${bridgeInterface} starts with the radio only"
            exit 0
          fi
          ip link set dev ${applianceInterface} master ${bridgeInterface}
          ip link set dev ${applianceInterface} up
        '';
      };

      # STP is off on a freshly created bridge, and with it off the kernel puts
      # ports straight into forwarding. Pinned anyway, and asserted by the test:
      # if a kernel ever did apply the default 15-second forward delay here, the
      # symptom would be a phone whose first DHCPDISCOVER is swallowed and which
      # then self-assigns a 169.254 address -- a failure that looks like a broken
      # AP rather than like a bridge timer.
      systemd.services.loom-bridge-tune = {
        description = "Pin forwarding behaviour on the appliance bridge";
        wantedBy = [ "network.target" ];
        after = [ "${bridgeInterface}-netdev.service" ];
        before = [ "network-addresses-${bridgeInterface}.service" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          echo 0 >/sys/class/net/${bridgeInterface}/bridge/stp_state
          echo 0 >/sys/class/net/${bridgeInterface}/bridge/forward_delay
        '';
      };

      # dnsmasq binds an address rather than an interface name (bind-interfaces),
      # so it has to start after that address exists on the bridge.
      systemd.services.dnsmasq = {
        after = [ "network-addresses-${bridgeInterface}.service" ];
        wants = [ "network-addresses-${bridgeInterface}.service" ];
      };
    })

    # -------------------------------------------------------------------------
    # Setup mode: ordinary client, so skaffold can reach the registries.
    # -------------------------------------------------------------------------
    (lib.mkIf (!isRun) {
      networking.useDHCP = lib.mkForce true;
      services.dnsmasq.enable = false;
    })

    # -------------------------------------------------------------------------
    # A stable name for the appliance NIC, in both modes.
    #
    # .link files are applied by udev whether or not systemd-networkd is running
    # (nixpkgs says so in networkd.nix, right above the option), so this works
    # alongside the scripted/dhcpcd networking the appliance actually uses.
    # -------------------------------------------------------------------------
    {
      systemd.network.links."10-${applianceInterface}" = {
        matchConfig = netMatch;
        linkConfig.Name = applianceInterface;
      };

      # If the match is wrong, everything above silently does nothing and the box
      # comes up unreachable -- with no sshd, the console is the only way to find
      # out why. Say so there, loudly, rather than leaving someone to guess.
      systemd.services.loom-network-check = {
        description = "Warn when the appliance interface is missing";
        wantedBy = [ "multi-user.target" ];
        after = [ "systemd-udev-settle.service" ];
        before = [ "loom.service" ];
        # Same ordering trick as box.nix's loom-issue.service, and for the same
        # reason: the warning below is written as an issue fragment, so it has
        # to exist before any getty renders the issue. getty-pre.target is
        # passive, hence `wants` as well as `before`.
        wants = [ "getty-pre.target" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          # Journal only. This used to be "journal+console", which -- with no
          # `console=` on the command line -- put it on the active VT. See
          # modes.nix for why that had to stop. The warning still reaches
          # somebody standing at the box, through the issue fragment below,
          # which is a better place for it: the login screen holds it until a
          # key is pressed instead of scrolling it past at boot.
          StandardOutput = "journal";
          StandardError = "journal";
        };
        # Never fails: this is a diagnostic, and blocking the boot of an
        # appliance whose only interface is missing helps nobody.
        script = ''
          if [ -e /sys/class/net/${applianceInterface} ]; then
            exit 0
          fi

          # Sorts after box.nix's 50-loom.issue, so this lands under the banner
          # and above agetty's press-ENTER prompt. No backslashes anywhere in
          # the text: agetty reads them as issue escapes. Written through a
          # temporary file for the same reason loom-issue.service is -- a getty
          # respawning mid-write must never read half a warning.
          mkdir -p /run/issue.d
          {
            echo "[!] ${applianceInterface} does not exist -- no address, no DHCP, no *.loom."
            echo "[!] The platform's interface match did not select anything. Present instead:"
            for candidate in /sys/class/net/*; do
              name="$(basename "$candidate")"
              [ "$name" = lo ] && continue
              echo "[!]   $name"
            done
            echo "[!] Rebuild the image with --interface <name> to pin one of the above."
          } > /run/issue.d/60-loom-network.issue.tmp
          mv /run/issue.d/60-loom-network.issue.tmp /run/issue.d/60-loom-network.issue

          # And to the journal, so `journalctl -u loom-network-check` still has it.
          cat /run/issue.d/60-loom-network.issue
          exit 0
        '';
      };
    }

    # -------------------------------------------------------------------------
    # Radios off in both modes.
    #
    # Software disable, module blacklist and an rfkill block. Generic on purpose
    # -- this covers the Spark's radios and the EVO-X2's MediaTek Wi-Fi/BT alike.
    # A firmware-level disable in the box's own BIOS is the only true guarantee
    # and is a documented manual step -- see Documentation/appliance.md.
    #
    # Bluetooth is unconditional. --wifi opts a box into an access point, not
    # into a radio free-for-all, and nothing in Loom has ever wanted BT.
    # -------------------------------------------------------------------------
    {
      # wpa_supplicant, i.e. joining someone else's network. Never wanted, in
      # either build: the access point is hostapd, which is the other direction.
      networking.wireless.enable = false;
      networking.networkmanager.enable = false;
      hardware.bluetooth.enable = false;

      boot.blacklistedKernelModules = [
        "bluetooth"
        "btusb"
        "btintel"
        "btbcm"
        "btrtl"
      ]
      # The 802.11 stack itself, without which hostapd has nothing to drive.
      # Dropping these two from the blacklist is the whole of what --wifi
      # unblanks at the kernel level.
      ++ lib.optionals (!wifiEnabled) [
        "cfg80211"
        "mac80211"
      ];

      systemd.services.loom-rfkill-block = {
        description = if wifiEnabled then "Hard-block bluetooth" else "Hard-block all radios";
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          # `rfkill block` exits non-zero when there is nothing to block, which
          # on a box with the modules blacklisted is the expected case.
          ExecStart = "${pkgs.util-linux}/bin/rfkill block ${if wifiEnabled then "bluetooth" else "all"}";
          SuccessExitStatus = [
            0
            1
          ];
        };
      };
    }
  ];
}
