# The appliance's optional access point.
#
# Off unless the image was built with `build-appliance-image --wifi`, in which
# case the box brings up its own WPA-protected network and bridges it onto the
# same segment as the wired port. A visitor who joins over the air lands in the
# same DHCP pool, behind the same resolver, at the same https://frontend.loom as
# one who plugs a cable in -- see network.nix, which owns the bridge.
#
# What this costs is stated plainly in Documentation/appliance.md and is worth
# repeating here: Loom has no user management and its frontend is not an
# authentication boundary, so with the radio on, the passphrase below is the
# only thing between the indexed corpus and everyone in range of the box.
#
# The credentials are generated once, by the build script, and baked into the
# closure. They are therefore world-readable in /nix/store and present on the
# USB stick. That is a deliberate trade: the operator learns the SSID and the
# passphrase from `build-appliance-image` before the box has ever been booted.
{
  config,
  lib,
  pkgs,
  enableWifi,
  wifiSsid,
  wifiPsk,
  wifiCountry,
  wifiInterface,
  ...
}:
let
  cfg = config.loom;

  # Same reasoning as network.nix's `loom0`: the appliance never refers to a
  # kernel-assigned name. udev renames whatever the platform matches to this,
  # and hostapd, the bridge and the banner all pin to it.
  wifiIface = "loomwl0";

  # `wifiInterface` is the escape hatch, exactly like `loomInterface` next door:
  # empty means "use the platform's match".
  wifiMatch =
    if wifiInterface != "" then { OriginalName = wifiInterface; } else cfg.platform.wifiMatch;

  isRun = cfg.mode == "run";
  active = cfg.wifi.enable && isRun;
in
{
  options.loom.wifi = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = enableWifi;
      description = ''
        Run an access point on the box's own radio, bridged onto the wired
        segment. Set by `build-appliance-image --wifi`; off in every other image,
        which is what keeps network.nix's blanket radio block in force.
      '';
    };

    ssid = lib.mkOption {
      type = lib.types.str;
      default = wifiSsid;
      description = "Network name to advertise. Generated by the build script.";
    };

    psk = lib.mkOption {
      type = lib.types.str;
      default = wifiPsk;
      description = ''
        The WPA passphrase. Generated by the build script from the same alphabet
        as the LUKS recovery passphrase (installer/loom_installer/install.py), which is
        not a coincidence: that alphabet excludes `\ ; : , "`, the exact set the
        `WIFI:` URI on the login screen would otherwise have to escape, and a
        backslash in an issue file is eaten by agetty before anyone sees it.
      '';
    };

    country = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = if wifiCountry == "" then null else wifiCountry;
      description = ''
        ISO 3166-1 country code, from `--wifi-country`. Null keeps the radio on
        2.4GHz under regulatory domain 00, which is legal everywhere; setting it
        moves the AP to 5GHz UNII-1.

        This is not a formality that 5GHz could be talked out of. Under domain 00
        every 5GHz sub-band is flagged NO-IR -- No Initiating Radiation -- which
        permits joining a network someone else started but forbids beaconing, so
        hostapd cannot bring an AP up at all. `iw reg get` shows it on any box.
      '';
    };

    interface = lib.mkOption {
      type = lib.types.str;
      default = wifiIface;
      readOnly = true;
      description = "The radio's name after udev has renamed it.";
    };

    bridge = lib.mkOption {
      type = lib.types.str;
      default = "loombr0";
      readOnly = true;
      description = ''
        The bridge carrying both the radio and the wired NIC. network.nix puts
        the appliance address on this instead of on loom0 when the AP is enabled.
      '';
    };
  };

  config = lib.mkMerge [
    {
      assertions = [
        {
          assertion = cfg.wifi.enable -> wifiMatch != null;
          message =
            "nixos: --wifi was given, but platform '${cfg.platform.id}' declares no wifiMatch, "
            + "so there is no radio to run an access point on. Pass --wifi-interface <name> to "
            + "name one explicitly, or build this platform without --wifi.";
        }
        {
          # hostapd's own assertions would catch a short one, but only after a
          # full closure evaluation and with a message about hostapd rather than
          # about the flag the operator actually passed.
          assertion = cfg.wifi.enable -> (builtins.stringLength cfg.wifi.psk >= 8);
          message = "nixos: --wifi-psk must be at least 8 characters (WPA minimum).";
        }
        {
          assertion = cfg.wifi.enable -> cfg.wifi.ssid != "";
          message = "nixos: --wifi requires a non-empty --wifi-ssid.";
        }
        {
          # Not style policing. Both strings are interpolated into the `WIFI:`
          # URI the login screen renders as a QR code, a format that reserves
          # `\ ; : , "` and escapes them with a backslash -- and a backslash in
          # an issue file is consumed by agetty as an escape of its own before it
          # reaches the screen (box.nix). Restricting the alphabet is what lets
          # that interpolation stay escape-free and correct. The build script
          # generates from a narrower set still; this catches a hand-passed
          # --wifi-ssid or --wifi-psk.
          assertion =
            cfg.wifi.enable
            -> (
              builtins.match "[A-Za-z0-9_-]+" cfg.wifi.ssid != null
              && builtins.match "[A-Za-z0-9_-]+" cfg.wifi.psk != null
            );
          message =
            "nixos: --wifi-ssid and --wifi-psk may only contain letters, digits, '-' and '_'. "
            + "Anything else cannot be put on the console QR code without an escape the console eats.";
        }
      ];
    }

    # -------------------------------------------------------------------------
    # The access point. Run mode only.
    #
    # Setup mode is an ordinary DHCP client that needs real internet exactly once
    # (network.nix) and runs no dnsmasq, so an AP there would advertise a network
    # that resolves nothing. The installer stick never imports this module at all.
    # -------------------------------------------------------------------------
    (lib.mkIf active {
      # Same trick, and the same caveat, as network.nix's rename of the wired
      # NIC: .link files are applied by udev whether or not networkd runs.
      systemd.network.links."10-${wifiIface}" = {
        matchConfig = wifiMatch;
        linkConfig.Name = wifiIface;
      };

      services.hostapd = {
        enable = true;
        radios.${wifiIface} = {
          # 2.4GHz unless a country code says otherwise. Slower, but channel
          # 1-11 is the only thing regulatory domain 00 lets an AP beacon on --
          # see `country` above.
          band = if cfg.wifi.country == null then "2g" else "5g";
          # A fixed channel rather than ACS (channel = 0): automatic channel
          # selection needs the driver to support ACS surveys, and a box that
          # silently fails to pick a channel is indistinguishable from one whose
          # radio does not do AP mode. 6 is the middle non-overlapping 2.4GHz
          # channel; 36 is the bottom of UNII-1, which is non-DFS everywhere it
          # is allocated at all, so the AP never waits out a radar CAC.
          channel = if cfg.wifi.country == null then 6 else 36;
          countryCode = cfg.wifi.country;

          # 802.11n. Visitors are uploading documents into a search engine, and
          # 802.11g alone would cap that near 20 Mbit/s.
          wifi4.enable = true;

          networks.${wifiIface} = {
            ssid = cfg.wifi.ssid;

            # Transition mode, not plain WPA3. The point of this feature is that
            # an unknown visitor's phone joins by scanning a QR code off the
            # monitor, and a WPA3-only AP silently excludes anything too old to
            # do SAE. hostapd's own default of ieee80211w = 1 keeps management
            # frame protection optional, which is what lets both generations
            # associate; forcing it would put the WPA2 half back out.
            authentication = {
              mode = "wpa3-sae-transition";
              # Both halves are required in transition mode. Already in the
              # store by construction -- see the header.
              wpaPassword = cfg.wifi.psk;
              saePasswords = [ { password = cfg.wifi.psk; } ];
            };

            # Clients have no reason to talk to each other -- every one of them
            # is here to reach the box -- and a room full of strangers' laptops
            # on one segment is not something to arrange on purpose.
            apIsolate = true;

            # hostapd enslaves its own interface on startup. Doing it here rather
            # than listing the radio in `networking.bridges` is deliberate: the
            # scripted bridge BindsTo each member's .device unit, so naming a
            # radio that has not appeared yet would take the whole bridge -- and
            # with it the wired network -- down with it.
            settings.bridge = cfg.wifi.bridge;
          };
        };
      };

      # network.nix blocks bluetooth rather than everything when the AP is on,
      # but firmware can still hand us a soft-blocked radio, and hostapd will not
      # unblock one itself: it just fails to bring the interface up.
      systemd.services.loom-rfkill-unblock-wifi = {
        description = "Release any soft block on the appliance radio";
        wantedBy = [ "multi-user.target" ];
        before = [ "hostapd.service" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = "${pkgs.util-linux}/bin/rfkill unblock wifi";
          # Nothing to unblock is the normal case, and rfkill exits non-zero for
          # it exactly as it does for `block all` in network.nix.
          SuccessExitStatus = [
            0
            1
          ];
        };
      };

      # ---------------------------------------------------------------------
      # Say so on the console when the AP did not come up.
      #
      # This matters more here than for the wired NIC. hostapd BindsTo the
      # radio's .device unit, so a wrong match, a missing card or a radio that
      # cannot do AP mode all produce the same silent outcome: hostapd never
      # starts, no error reaches anyone, and the login screen goes on printing an
      # SSID and a QR code for a network that does not exist. On a box with no
      # sshd, the issue file is the only place that can be corrected.
      #
      # Same shape as network.nix's loom-network-check, for the same reasons --
      # including the ordering against getty-pre.target and the refusal to fail.
      # ---------------------------------------------------------------------
      systemd.services.loom-wifi-check = {
        description = "Warn when the appliance access point is missing";
        wantedBy = [ "multi-user.target" ];
        after = [
          "systemd-udev-settle.service"
          "hostapd.service"
        ];
        # `before` names getty-pre.target as well as loom.service: `wants` pulls
        # the target into the transaction but orders nothing against it, and the
        # fragment written below is the one thing that corrects a login banner
        # still printing an SSID and a QR code for an access point that never
        # came up. See network.nix's loom-network-check.
        wants = [ "getty-pre.target" ];
        before = [
          "loom.service"
          "getty-pre.target"
        ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          StandardOutput = "journal";
          StandardError = "journal";
        };
        # No backslashes anywhere below: agetty reads them as issue escapes.
        script = ''
          # Sorts after network.nix's 60-loom-network.issue, so a box that is
          # wrong about both reports the wired problem first.
          report() {
            mkdir -p /run/issue.d
            cat >/run/issue.d/61-loom-wifi.issue.tmp
            mv /run/issue.d/61-loom-wifi.issue.tmp /run/issue.d/61-loom-wifi.issue
            cat /run/issue.d/61-loom-wifi.issue
          }

          if [ ! -e /sys/class/net/${wifiIface} ]; then
            {
              echo "[!] ${wifiIface} does not exist -- this box has no access point."
              echo "[!] The platform's radio match did not select anything. Present instead:"
              for candidate in /sys/class/net/*; do
                name="$(basename "$candidate")"
                [ "$name" = lo ] && continue
                echo "[!]   $name"
              done
              echo "[!] Rebuild with --wifi-interface <name>, or without --wifi."
              echo "[!] The wired port still works."
            } | report
            exit 0
          fi

          if ! systemctl is-active --quiet hostapd.service; then
            {
              echo "[!] ${wifiIface} exists but hostapd is not running -- no access point."
              echo "[!] The usual cause is a radio that does not support AP mode. Check with:"
              echo "[!]   iw list | grep -A15 'Supported interface modes'"
              echo "[!] and look for a line reading '* AP'. Then: journalctl -u hostapd"
              echo "[!] The wired port still works."
            } | report
            exit 0
          fi

          # Came up. Clear any fragment a previous boot left behind.
          rm -f /run/issue.d/61-loom-wifi.issue
          exit 0
        '';
      };
    })
  ];
}
