apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app.fullname" . }}-seaweedfs-volume-pdb
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "seaweedfs") | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-seaweedfs-volume
