apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-libretranslate
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: libretranslate
spec:
  ports:
    - port: {{ .Values.libretranslate.service.port }}
      name: libretranslate
      targetPort: {{ .Values.libretranslate.service.port }}
  selector:
    app: {{ include "app.name" . }}-libretranslate
