apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-roundcube
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: roundcube
spec:
  ports:
    - port: {{ .Values.roundcube.service.port }}
      name: roundcube
      targetPort: {{ .Values.roundcube.service.port }}
  selector:
    app: {{ include "app.name" . }}-roundcube
