{{- if .Values.rabbit.ingress.amqp.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "app.fullname" . }}-rabbit-amqp
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rabbit
spec:
  entryPoints:
    - amqp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "app.fullname" . }}-rabbit
          port: {{ .Values.rabbit.service.port.amqp }}
{{- end }}