{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}-kube-state-metrics
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "kubeStateMetrics") | nindent 4 }}
    app.kubernetes.io/component: monitoring
{{- end }}
