{{- if .Values.externalSecrets.archiveEncMasterKey.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: archive-enc-master-key
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "") | nindent 4 }}
  {{- with include "app.annotations.custom" (dict "context" . "component" "") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: archive-enc-master-key
  data:
    - secretKey: secretkey
      remoteRef:
        key: {{ .Values.externalSecrets.archiveEncMasterKey.remoteRef.key }}
        property: {{ .Values.externalSecrets.archiveEncMasterKey.remoteRef.property }}
{{- end }}
