{{- range $secretKey, $secret := .Values.externalSecrets.secrets }}
{{- if $secret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
  labels:
    {{- include "app.labels.custom" (dict "context" $ "component" "") | nindent 4 }}
  {{- with include "app.annotations.custom" (dict "context" $ "component" "") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ $secret.name }}
  data:
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $secret.remoteRef.key }}
        property: {{ $secret.remoteRef.property }}
{{- end }}
{{- end }}
