{{- if .Values.globalHttpRedirect.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  labels:
    ingressclass: traefik
  name: {{ include "app.fullname" . }}-global-http-redirect
spec:
  redirectScheme:
    scheme: https
{{- end }}
