apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-persister
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "worker") | nindent 4 }}
    app.kubernetes.io/component: "persister"
spec:
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: {{ .Values.persister.service.port }}
      name: persister
      targetPort: {{ .Values.persister.service.port }}
  selector:
    app: {{ include "app.name" . }}-persister
