apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}-persister
  labels:
    {{- include "app.labels.custom" (dict "context" . "component" "worker") | nindent 4 }}
    app.kubernetes.io/component: "persister"
spec:
  serviceName: {{ include "app.fullname" . }}-persister
  podManagementPolicy: Parallel
  replicas: {{ .Values.persister.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-persister
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-persister
        {{- include "app.labels.custom" (dict "context" . "component" "worker") | nindent 8 }}
    spec:
      containers:
        - name: persister
          image: {{ .Values.image.registry }}/{{ .Values.persister.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.persister.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: persister
              containerPort: {{ .Values.persister.service.port }}
          env:
            - name: WORKER_TYPE
              value: "PERSISTER"
            - name: archive_enc_master_key
              valueFrom:
                secretKeyRef:
                  name: archive-enc-master-key
                  key: secretkey
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-settings
          {{- if .Values.persister.command }}
          command: {{- toYaml .Values.persister.command | nindent 12 }}
          {{- else }}
          command:
            - "python"
            - "main.py"
            - "worker"
            - "--loglevel"
            - "INFO"
          {{- end }}
          {{- if .Values.persister.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - WORKER_TYPE=INSPECT python main.py inspect ping --timeout 99999 --destination "celery@${HOSTNAME}"
            initialDelaySeconds: {{ default 10 .Values.persister.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 120 .Values.persister.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ default 60 .Values.persister.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ default 6 .Values.persister.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.persister.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - WORKER_TYPE=INSPECT python main.py inspect ping --timeout 99999 --destination "celery@${HOSTNAME}"
            initialDelaySeconds: {{ default 10 .Values.persister.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 120 .Values.persister.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ default 60 .Values.persister.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ default 6 .Values.persister.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.persister.resources }}
          resources: {{- toYaml .Values.persister.resources | nindent 12 }}
          {{- end }}
