apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-celery-worker
  labels:
    {{- include "app.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "celery"
spec:
  {{- if not .Values.celery.worker.main.hpa.enabled }}
  replicas: {{ .Values.celery.worker.main.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-celery-worker
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-celery-worker
    spec:
      containers:
        - name: celery-worker
          image: {{ .Values.image.registry }}/{{ .Values.celery.worker.main.image.repository }}:{{ default (default .Chart.AppVersion .Values.image.tag) .Values.celery.worker.main.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: worker
              containerPort: {{ .Values.celery.worker.main.service.port }}
          env:
            - name: archive_encryption_master_key
              valueFrom:
                secretKeyRef:
                  name: archive-encryption-master-key
                  key: secretkey
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-settings
          {{- if .Values.celery.worker.main.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - python -m celery -A worker inspect ping -t 99999 -d "celery@$HOSTNAME"
            initialDelaySeconds: {{ default 0 .Values.celery.worker.main.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 30 .Values.celery.worker.main.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ default 10 .Values.celery.worker.main.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ default 3 .Values.celery.worker.main.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.celery.worker.main.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - python -m celery -A worker inspect ping -t 99999 -d "celery@$HOSTNAME"
            initialDelaySeconds: {{ default 0 .Values.celery.worker.main.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 120 .Values.celery.worker.main.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ default 60 .Values.celery.worker.main.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ default 6 .Values.celery.worker.main.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.celery.worker.main.resources }}
          resources: {{- toYaml .Values.celery.worker.main.resources | nindent 12 }}
          {{- end }}
