import { TourStep } from "./types";

export const TOUR_TARGETS = {
    activityBar: '[data-tour="activity-bar"]',
    activityBarLeft: '[data-tour="activity-bar-left"]',
    activityBarRight: '[data-tour="activity-bar-right"]',
    cardCustomization: '[data-tour="sidebar-card-customization"]',
    cardCustomizationDisplay: '[data-tour="card-customization-display"]',
    cardCustomizationFields: '[data-tour="card-customization-fields"]',
    cardCustomizationAutoActions:
        '[data-tour="card-customization-auto-actions"]',
    branding: '[data-tour="branding"]',
    bulkActions: '[data-tour="sidebar-bulk-actions"]',
    fileDetail: '[data-tour="sidebar-file-detail"]',
    chat: '[data-tour="sidebar-chat"]',
    detailHighlights: '[data-tour="detail-highlights"]',
    detailRaw: '[data-tour="detail-raw"]',
    detailRendered: '[data-tour="detail-rendered"]',
    detailTranslations: '[data-tour="detail-translations"]',
    documentDetail: '[data-tour="document-detail"]',
    folderFilter: '[data-tour="sidebar-folder-filter"]',
    upload: '[data-tour="upload"]',
    folderTreeNode: '[data-tour="folder-tree-node"]',
    filteredFolder: '[data-tour="sidebar-filtered-folder"]',
    folders: '[data-tour="sidebar-folders"]',
    globalSearch: '[data-tour="global-search"]',
    keyboardShortcuts: '[data-tour="keyboard-shortcuts"]',
    menu: '[data-tour="menu"]',
    menuAbout: '[data-tour="menu-about"]',
    navigation: '[data-tour="navigation"]',
    processingStatus: '[data-tour="processing-status"]',
    queryOverview: '[data-tour="query-overview"]',
    resultCard: '[data-tour="result-card"]',
    resultCardActions: '[data-tour="result-card-actions"]',
    resultCardContent: '[data-tour="result-card-content"]',
    resultCardPath: '[data-tour="result-card-path"]',
    resultCardProcessingStatus: '[data-tour="result-card-processing-status"]',
    resultCardPreview: '[data-tour="result-card-preview"]',
    resultCardSubitems: '[data-tour="result-card-subitems"]',
    resultCardTags: '[data-tour="result-card-tags"]',
    resultsTabs: '[data-tour="results-tabs"]',
    savedQueries: '[data-tour="sidebar-saved-queries"]',
    searchAllQuery: '[data-tour="search-all-query"]',
    statistics: '[data-tour="sidebar-statistics"]',
    statisticsHistogram: '[data-tour="statistics-histogram"]',
    statisticsPieChart: '[data-tour="statistics-pie-chart"]',
    tags: '[data-tour="sidebar-tags"]',
    archivesTab: '[data-tour="archives-tab"]',
    encryptionKeyDisplay: '[data-tour="encryption-key-display"]',
    createArchiveButton: '[data-tour="create-archive-button"]',
    archivesList: '[data-tour="archives-list"]',
    archiveUpload: '[data-tour="archive-upload"]',
    archiveDownloadButton: '[data-tour="archive-download-button"]',
    activityBarFolders: '[data-tour="activity-bar-folders"]',
    activityBarTags: '[data-tour="activity-bar-tags"]',
    activityBarSavedQueries: '[data-tour="activity-bar-saved-queries"]',
    chatMessages: '[data-tour="chat-messages"]',
    chatInput: '[data-tour="chat-input"]',
    chatHistoryButton: '[data-tour="chat-history-button"]',
    chatNewButton: '[data-tour="chat-new-button"]',
    chatDeepSearch: '[data-tour="chat-deep-search"]',
} as const;

export const INCREMENTAL_TOUR_INTRO_STEP: TourStep = {
    id: "incremental-welcome",
    target: { selector: TOUR_TARGETS.branding },
    titleKey: "tour.steps.incrementalWelcome.title",
    descriptionKey: "tour.steps.incrementalWelcome.description",
    side: "bottom",
    align: "start",
};

export const TOUR_CONCLUSION_STEP: TourStep = {
    id: "conclusion",
    target: { selector: TOUR_TARGETS.branding },
    titleKey: "tour.steps.conclusion.title",
    descriptionKey: "tour.steps.conclusion.description",
    side: "bottom",
    align: "start",
};

export const GLOBAL_TOUR_STEPS: readonly TourStep[] = [
    {
        id: "welcome",
        target: { selector: TOUR_TARGETS.branding },
        titleKey: "tour.steps.welcome.title",
        descriptionKey: "tour.steps.welcome.description",
        side: "bottom",
        align: "start",
    },
    {
        id: "global-search",
        target: { selector: TOUR_TARGETS.globalSearch },
        titleKey: "tour.steps.globalSearch.title",
        descriptionKey: "tour.steps.globalSearch.description",
        side: "bottom",
        align: "center",
    },
    {
        id: "query-overview",
        target: { selector: TOUR_TARGETS.queryOverview },
        titleKey: "tour.steps.queryOverview.title",
        descriptionKey: "tour.steps.queryOverview.description",
        side: "right",
        align: "start",
    },
    {
        id: "keyboard-shortcuts",
        target: { selector: TOUR_TARGETS.keyboardShortcuts },
        titleKey: "tour.steps.keyboardShortcuts.title",
        descriptionKey: "tour.steps.keyboardShortcuts.description",
        side: "left",
        align: "start",
    },
    {
        id: "search-all",
        target: { selector: TOUR_TARGETS.searchAllQuery },
        titleKey: "tour.steps.searchAll.title",
        descriptionKey: "tour.steps.searchAll.description",
        nextButtonKey: "tour.controls.searchAll",
        side: "right",
        align: "start",
    },
    {
        id: "results-tabs",
        target: { selector: TOUR_TARGETS.resultsTabs },
        titleKey: "tour.steps.resultsTabs.title",
        descriptionKey: "tour.steps.resultsTabs.description",
        preparation: "search-results",
        side: "bottom",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card",
        target: { selector: TOUR_TARGETS.resultCard },
        titleKey: "tour.steps.resultCard.title",
        descriptionKey: "tour.steps.resultCard.description",
        preparation: "search-results",
        side: "right",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card-path",
        target: { selector: TOUR_TARGETS.resultCardPath },
        titleKey: "tour.steps.resultCardPath.title",
        descriptionKey: "tour.steps.resultCardPath.description",
        preparation: "search-results",
        side: "bottom",
        align: "start",
    },
    {
        id: "result-card-processing-status",
        target: { selector: TOUR_TARGETS.resultCardProcessingStatus },
        titleKey: "tour.steps.resultCardProcessingStatus.title",
        descriptionKey: "tour.steps.resultCardProcessingStatus.description",
        preparation: "search-results",
        side: "bottom",
        align: "start",
    },
    {
        id: "result-card-subitems",
        target: { selector: TOUR_TARGETS.resultCardSubitems },
        titleKey: "tour.steps.resultCardSubitems.title",
        descriptionKey: "tour.steps.resultCardSubitems.description",
        preparation: "search-results",
        side: "bottom",
        align: "start",
    },
    {
        id: "result-card-content",
        target: { selector: TOUR_TARGETS.resultCardContent },
        titleKey: "tour.steps.resultCardContent.title",
        descriptionKey: "tour.steps.resultCardContent.description",
        preparation: "search-results",
        side: "right",
        align: "start",
    },
    {
        id: "result-card-tags",
        target: { selector: TOUR_TARGETS.resultCardTags },
        titleKey: "tour.steps.resultCardTags.title",
        descriptionKey: "tour.steps.resultCardTags.description",
        preparation: "search-results",
        side: "top",
        align: "end",
    },
    {
        id: "result-card-actions",
        target: { selector: TOUR_TARGETS.resultCardActions },
        titleKey: "tour.steps.resultCardActions.title",
        descriptionKey: "tour.steps.resultCardActions.description",
        preparation: "search-results",
        side: "left",
        align: "end",
    },
    {
        id: "result-card-preview",
        target: { selector: TOUR_TARGETS.resultCardPreview },
        titleKey: "tour.steps.resultCardPreview.title",
        descriptionKey: "tour.steps.resultCardPreview.description",
        preparation: "search-results",
        side: "left",
        align: "center",
    },
    {
        id: "document-detail",
        target: { selector: TOUR_TARGETS.documentDetail },
        titleKey: "tour.steps.documentDetail.title",
        descriptionKey: "tour.steps.documentDetail.description",
        preparation: "search-results",
        side: "bottom",
        align: "center",
        waitForElementMs: 2_000,
    },
    {
        id: "detail-rendered",
        target: { selector: TOUR_TARGETS.detailRendered },
        titleKey: "tour.steps.detailRendered.title",
        descriptionKey: "tour.steps.detailRendered.description",
        preparation: "search-results",
        side: "bottom",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "detail-translations",
        target: { selector: TOUR_TARGETS.detailTranslations },
        titleKey: "tour.steps.detailTranslations.title",
        descriptionKey: "tour.steps.detailTranslations.description",
        preparation: "search-results",
        side: "bottom",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "detail-highlights",
        target: { selector: TOUR_TARGETS.detailHighlights },
        titleKey: "tour.steps.detailHighlights.title",
        descriptionKey: "tour.steps.detailHighlights.description",
        preparation: "search-results",
        side: "bottom",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "detail-raw",
        target: { selector: TOUR_TARGETS.detailRaw },
        titleKey: "tour.steps.detailRaw.title",
        descriptionKey: "tour.steps.detailRaw.description",
        preparation: "search-results",
        side: "bottom",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "activity-bar-left",
        target: { selector: TOUR_TARGETS.activityBarLeft },
        titleKey: "tour.steps.activityBarLeft.title",
        descriptionKey: "tour.steps.activityBarLeft.description",
        side: "right",
        align: "start",
    },
    {
        id: "upload",
        target: { selector: TOUR_TARGETS.upload },
        titleKey: "tour.steps.upload.title",
        descriptionKey: "tour.steps.upload.description",
        side: "right",
        align: "start",
    },
    {
        id: "folder-icon",
        target: { selector: TOUR_TARGETS.activityBarFolders },
        titleKey: "tour.steps.folderIcon.title",
        descriptionKey: "tour.steps.folderIcon.description",
        side: "right",
        align: "start",
    },
    {
        id: "folders",
        target: { selector: TOUR_TARGETS.folders },
        titleKey: "tour.steps.folders.title",
        descriptionKey: "tour.steps.folders.description",
        side: "right",
        align: "start",
    },
    {
        id: "folder-tree-node",
        target: { selector: TOUR_TARGETS.folderTreeNode },
        titleKey: "tour.steps.folderTreeNode.title",
        descriptionKey: "tour.steps.folderTreeNode.description",
        side: "right",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "folder-filter",
        target: { selector: TOUR_TARGETS.folderFilter },
        titleKey: "tour.steps.folderFilter.title",
        descriptionKey: "tour.steps.folderFilter.description",
        side: "right",
        align: "start",
    },
    {
        id: "tags-icon",
        target: { selector: TOUR_TARGETS.activityBarTags },
        titleKey: "tour.steps.tagsIcon.title",
        descriptionKey: "tour.steps.tagsIcon.description",
        side: "right",
        align: "start",
    },
    {
        id: "tags",
        target: { selector: TOUR_TARGETS.tags },
        titleKey: "tour.steps.tags.title",
        descriptionKey: "tour.steps.tags.description",
        side: "right",
        align: "start",
    },
    {
        id: "saved-queries-icon",
        target: { selector: TOUR_TARGETS.activityBarSavedQueries },
        titleKey: "tour.steps.savedQueriesIcon.title",
        descriptionKey: "tour.steps.savedQueriesIcon.description",
        side: "right",
        align: "start",
    },
    {
        id: "saved-queries",
        target: { selector: TOUR_TARGETS.savedQueries },
        titleKey: "tour.steps.savedQueries.title",
        descriptionKey: "tour.steps.savedQueries.description",
        side: "right",
        align: "start",
    },
    {
        id: "card-customization",
        target: { selector: TOUR_TARGETS.cardCustomization },
        titleKey: "tour.steps.cardCustomization.title",
        descriptionKey: "tour.steps.cardCustomization.description",
        side: "right",
        align: "start",
    },
    {
        id: "card-customization-display",
        target: { selector: TOUR_TARGETS.cardCustomizationDisplay },
        titleKey: "tour.steps.cardCustomizationDisplay.title",
        descriptionKey: "tour.steps.cardCustomizationDisplay.description",
        side: "right",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "card-customization-fields",
        target: { selector: TOUR_TARGETS.cardCustomizationFields },
        titleKey: "tour.steps.cardCustomizationFields.title",
        descriptionKey: "tour.steps.cardCustomizationFields.description",
        side: "right",
        align: "start",
    },
    {
        id: "card-customization-auto-actions",
        target: { selector: TOUR_TARGETS.cardCustomizationAutoActions },
        titleKey: "tour.steps.cardCustomizationAutoActions.title",
        descriptionKey: "tour.steps.cardCustomizationAutoActions.description",
        side: "right",
        align: "start",
    },
    {
        id: "chat",
        target: { selector: TOUR_TARGETS.chat },
        titleKey: "tour.steps.chat.title",
        descriptionKey: "tour.steps.chat.description",
        side: "right",
        align: "start",
    },
    {
        id: "chat-input",
        target: { selector: TOUR_TARGETS.chatInput },
        titleKey: "tour.steps.chatInput.title",
        descriptionKey: "tour.steps.chatInput.description",
        side: "top",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "chat-sources-warning",
        target: { selector: TOUR_TARGETS.chatMessages },
        titleKey: "tour.steps.chatSourcesWarning.title",
        descriptionKey: "tour.steps.chatSourcesWarning.description",
        side: "top",
        align: "start",
    },
    {
        id: "chat-deep-search",
        target: { selector: TOUR_TARGETS.chatDeepSearch },
        titleKey: "tour.steps.chatDeepSearch.title",
        descriptionKey: "tour.steps.chatDeepSearch.description",
        side: "top",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "chat-history",
        target: { selector: TOUR_TARGETS.chatHistoryButton },
        titleKey: "tour.steps.chatHistory.title",
        descriptionKey: "tour.steps.chatHistory.description",
        side: "bottom",
        align: "start",
    },
    {
        id: "chat-new-chat",
        target: { selector: TOUR_TARGETS.chatNewButton },
        titleKey: "tour.steps.chatNewChat.title",
        descriptionKey: "tour.steps.chatNewChat.description",
        side: "bottom",
        align: "start",
    },
    {
        id: "activity-bar-right",
        target: { selector: TOUR_TARGETS.activityBarRight },
        titleKey: "tour.steps.activityBarRight.title",
        descriptionKey: "tour.steps.activityBarRight.description",
        side: "right",
        align: "end",
    },
    {
        id: "file-detail",
        target: { selector: TOUR_TARGETS.fileDetail },
        titleKey: "tour.steps.fileDetail.title",
        descriptionKey: "tour.steps.fileDetail.description",
        side: "left",
        align: "start",
    },
    {
        id: "filtered-folder",
        target: { selector: TOUR_TARGETS.filteredFolder },
        titleKey: "tour.steps.filteredFolder.title",
        descriptionKey: "tour.steps.filteredFolder.description",
        preparation: "search-results",
        side: "left",
        align: "start",
    },
    {
        id: "statistics",
        target: { selector: TOUR_TARGETS.statistics },
        titleKey: "tour.steps.statistics.title",
        descriptionKey: "tour.steps.statistics.description",
        preparation: "search-results",
        side: "left",
        align: "start",
    },
    {
        id: "statistics-pie-chart",
        target: { selector: TOUR_TARGETS.statisticsPieChart },
        titleKey: "tour.steps.statisticsPieChart.title",
        descriptionKey: "tour.steps.statisticsPieChart.description",
        preparation: "search-results",
        side: "left",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "statistics-histogram",
        target: { selector: TOUR_TARGETS.statisticsHistogram },
        titleKey: "tour.steps.statisticsHistogram.title",
        descriptionKey: "tour.steps.statisticsHistogram.description",
        preparation: "search-results",
        side: "left",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "bulk-actions",
        target: { selector: TOUR_TARGETS.bulkActions },
        titleKey: "tour.steps.bulkActions.title",
        descriptionKey: "tour.steps.bulkActions.description",
        side: "left",
        align: "start",
    },
    {
        id: "bulk-action-create-archive",
        target: { selector: TOUR_TARGETS.createArchiveButton },
        titleKey: "tour.steps.bulkActionCreateArchive.title",
        descriptionKey: "tour.steps.bulkActionCreateArchive.description",
        side: "left",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "header-archives-tab",
        target: { selector: TOUR_TARGETS.archivesTab },
        titleKey: "tour.steps.headerArchivesTab.title",
        descriptionKey: "tour.steps.headerArchivesTab.description",
        nextButtonKey: "tour.controls.openArchives",
        side: "bottom",
        align: "end",
    },
    {
        id: "archives-list",
        target: { selector: TOUR_TARGETS.archivesList },
        titleKey: "tour.steps.archivesList.title",
        descriptionKey: "tour.steps.archivesList.description",
        side: "right",
        align: "start",
        waitForElementMs: 3_000,
        skipIfMissing: true,
        requiresPathname: "/archives",
    },
    {
        id: "archive-cli-intro",
        target: { selector: TOUR_TARGETS.archiveDownloadButton },
        titleKey: "tour.steps.archiveCliIntro.title",
        descriptionKey: "tour.steps.archiveCliIntro.description",
        side: "left",
        align: "start",
        waitForElementMs: 2_000,
        skipIfMissing: true,
        requiresPathname: "/archives",
    },
    {
        id: "archive-cli-demo",
        target: { selector: TOUR_TARGETS.archiveDownloadButton },
        titleKey: "tour.steps.archiveCliDemo.title",
        descriptionKey: "tour.steps.archiveCliDemo.description",
        side: "left",
        align: "start",
        waitForElementMs: 2_000,
        skipIfMissing: true,
        requiresPathname: "/archives",
    },
    {
        id: "archives-upload",
        target: { selector: TOUR_TARGETS.archiveUpload },
        titleKey: "tour.steps.archivesUpload.title",
        descriptionKey: "tour.steps.archivesUpload.description",
        side: "right",
        align: "start",
        waitForElementMs: 2_000,
        skipIfMissing: true,
        requiresPathname: "/archives",
    },
    {
        id: "encryption-key-display",
        target: { selector: TOUR_TARGETS.encryptionKeyDisplay },
        titleKey: "tour.steps.encryptionKeyDisplay.title",
        descriptionKey: "tour.steps.encryptionKeyDisplay.description",
        side: "bottom",
        align: "center",
        waitForElementMs: 2_000,
        skipIfMissing: true,
        requiresPathname: "/archives",
    },
    {
        id: "processing-status",
        target: { selector: TOUR_TARGETS.processingStatus },
        titleKey: "tour.steps.processingStatus.title",
        descriptionKey: "tour.steps.processingStatus.description",
        side: "bottom",
        align: "end",
    },
    {
        id: "menu",
        target: { selector: TOUR_TARGETS.menu },
        titleKey: "tour.steps.menu.title",
        descriptionKey: "tour.steps.menu.description",
        side: "bottom",
        align: "end",
        waitForElementMs: 2_000,
    },
    TOUR_CONCLUSION_STEP,
];
