import { TourStep } from "./types";

export const TOUR_TARGETS = {
    activityBar: '[data-tour="activity-bar"]',
    autoActions: '[data-tour="sidebar-auto-actions"]',
    branding: '[data-tour="branding"]',
    bulkActions: '[data-tour="sidebar-bulk-actions"]',
    chat: '[data-tour="sidebar-chat"]',
    detailHighlights: '[data-tour="detail-highlights"]',
    detailRaw: '[data-tour="detail-raw"]',
    detailRendered: '[data-tour="detail-rendered"]',
    detailTranslations: '[data-tour="detail-translations"]',
    documentDetail: '[data-tour="document-detail"]',
    folderFilter: '[data-tour="sidebar-folder-filter"]',
    folderTreeNode: '[data-tour="folder-tree-node"]',
    folders: '[data-tour="sidebar-folders"]',
    globalSearch: '[data-tour="global-search"]',
    keyboardShortcuts: '[data-tour="keyboard-shortcuts"]',
    menu: '[data-tour="menu"]',
    menuAbout: '[data-tour="menu-about"]',
    navigation: '[data-tour="navigation"]',
    processingStatus: '[data-tour="processing-status"]',
    queryOverview: '[data-tour="query-overview"]',
    resultCard: '[data-tour="result-card"]',
    resultCardActions: '[data-tour="result-card-actions"]',
    resultCardContent: '[data-tour="result-card-content"]',
    resultCardPath: '[data-tour="result-card-path"]',
    resultCardProcessingStatus: '[data-tour="result-card-processing-status"]',
    resultCardPreview: '[data-tour="result-card-preview"]',
    resultCardSubitems: '[data-tour="result-card-subitems"]',
    resultCardTags: '[data-tour="result-card-tags"]',
    resultsTabs: '[data-tour="results-tabs"]',
    savedQueries: '[data-tour="sidebar-saved-queries"]',
    searchAllQuery: '[data-tour="search-all-query"]',
    statistics: '[data-tour="sidebar-statistics"]',
    statisticsHistogram: '[data-tour="statistics-histogram"]',
    statisticsPieChart: '[data-tour="statistics-pie-chart"]',
    tags: '[data-tour="sidebar-tags"]',
} as const;

export const GLOBAL_TOUR_STEPS: readonly TourStep[] = [
    {
        id: "welcome",
        target: { selector: TOUR_TARGETS.branding },
        titleKey: "tour.steps.welcome.title",
        descriptionKey: "tour.steps.welcome.description",
        showSkipButton: true,
        side: "bottom",
        align: "start",
    },
    {
        id: "global-search",
        target: { selector: TOUR_TARGETS.globalSearch },
        titleKey: "tour.steps.globalSearch.title",
        descriptionKey: "tour.steps.globalSearch.description",
        side: "bottom",
        align: "center",
    },
    {
        id: "query-overview",
        target: { selector: TOUR_TARGETS.queryOverview },
        titleKey: "tour.steps.queryOverview.title",
        descriptionKey: "tour.steps.queryOverview.description",
        side: "right",
        align: "start",
    },
    {
        id: "keyboard-shortcuts",
        target: {
            selector: TOUR_TARGETS.keyboardShortcuts,
            viewport: "desktop",
        },
        titleKey: "tour.steps.keyboardShortcuts.title",
        descriptionKey: "tour.steps.keyboardShortcuts.description",
        side: "left",
        align: "start",
    },
    {
        id: "search-all",
        target: { selector: TOUR_TARGETS.searchAllQuery },
        titleKey: "tour.steps.searchAll.title",
        descriptionKey: "tour.steps.searchAll.description",
        nextButtonKey: "tour.controls.searchAll",
        side: "right",
        align: "start",
    },
    {
        id: "results-tabs",
        target: { selector: TOUR_TARGETS.resultsTabs },
        titleKey: "tour.steps.resultsTabs.title",
        descriptionKey: "tour.steps.resultsTabs.description",
        side: "bottom",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card",
        target: { selector: TOUR_TARGETS.resultCard },
        titleKey: "tour.steps.resultCard.title",
        descriptionKey: "tour.steps.resultCard.description",
        side: "right",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card-path",
        target: { selector: TOUR_TARGETS.resultCardPath, viewport: "desktop" },
        titleKey: "tour.steps.resultCardPath.title",
        descriptionKey: "tour.steps.resultCardPath.description",
        side: "bottom",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card-processing-status",
        target: {
            selector: TOUR_TARGETS.resultCardProcessingStatus,
            viewport: "desktop",
        },
        titleKey: "tour.steps.resultCardProcessingStatus.title",
        descriptionKey: "tour.steps.resultCardProcessingStatus.description",
        side: "bottom",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card-subitems",
        target: { selector: TOUR_TARGETS.resultCardSubitems },
        titleKey: "tour.steps.resultCardSubitems.title",
        descriptionKey: "tour.steps.resultCardSubitems.description",
        side: "bottom",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card-content",
        target: { selector: TOUR_TARGETS.resultCardContent },
        titleKey: "tour.steps.resultCardContent.title",
        descriptionKey: "tour.steps.resultCardContent.description",
        side: "right",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card-tags",
        target: { selector: TOUR_TARGETS.resultCardTags },
        titleKey: "tour.steps.resultCardTags.title",
        descriptionKey: "tour.steps.resultCardTags.description",
        side: "top",
        align: "end",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card-actions",
        target: { selector: TOUR_TARGETS.resultCardActions },
        titleKey: "tour.steps.resultCardActions.title",
        descriptionKey: "tour.steps.resultCardActions.description",
        side: "left",
        align: "end",
        waitForElementMs: 3_000,
    },
    {
        id: "result-card-preview",
        target: { selector: TOUR_TARGETS.resultCardPreview },
        titleKey: "tour.steps.resultCardPreview.title",
        descriptionKey: "tour.steps.resultCardPreview.description",
        side: "left",
        align: "center",
        waitForElementMs: 3_000,
    },
    {
        id: "document-detail",
        target: { selector: TOUR_TARGETS.documentDetail },
        titleKey: "tour.steps.documentDetail.title",
        descriptionKey: "tour.steps.documentDetail.description",
        side: "bottom",
        align: "center",
        waitForElementMs: 2_000,
    },
    {
        id: "detail-rendered",
        target: { selector: TOUR_TARGETS.detailRendered },
        titleKey: "tour.steps.detailRendered.title",
        descriptionKey: "tour.steps.detailRendered.description",
        side: "bottom",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "detail-translations",
        target: { selector: TOUR_TARGETS.detailTranslations },
        titleKey: "tour.steps.detailTranslations.title",
        descriptionKey: "tour.steps.detailTranslations.description",
        side: "bottom",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "detail-highlights",
        target: { selector: TOUR_TARGETS.detailHighlights },
        titleKey: "tour.steps.detailHighlights.title",
        descriptionKey: "tour.steps.detailHighlights.description",
        side: "bottom",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "detail-raw",
        target: { selector: TOUR_TARGETS.detailRaw },
        titleKey: "tour.steps.detailRaw.title",
        descriptionKey: "tour.steps.detailRaw.description",
        side: "bottom",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "activity-bar",
        target: { selector: TOUR_TARGETS.activityBar },
        titleKey: "tour.steps.activityBar.title",
        descriptionKey: "tour.steps.activityBar.description",
        side: "right",
        align: "start",
    },
    {
        id: "folders",
        target: { selector: TOUR_TARGETS.folders },
        titleKey: "tour.steps.folders.title",
        descriptionKey: "tour.steps.folders.description",
        side: "right",
        align: "start",
    },
    {
        id: "folder-tree-node",
        target: { selector: TOUR_TARGETS.folderTreeNode },
        titleKey: "tour.steps.folderTreeNode.title",
        descriptionKey: "tour.steps.folderTreeNode.description",
        side: "right",
        align: "start",
        waitForElementMs: 3_000,
    },
    {
        id: "folder-filter",
        target: { selector: TOUR_TARGETS.folderFilter },
        titleKey: "tour.steps.folderFilter.title",
        descriptionKey: "tour.steps.folderFilter.description",
        side: "right",
        align: "start",
    },
    {
        id: "tags",
        target: { selector: TOUR_TARGETS.tags },
        titleKey: "tour.steps.tags.title",
        descriptionKey: "tour.steps.tags.description",
        side: "right",
        align: "start",
    },
    {
        id: "saved-queries",
        target: { selector: TOUR_TARGETS.savedQueries },
        titleKey: "tour.steps.savedQueries.title",
        descriptionKey: "tour.steps.savedQueries.description",
        side: "right",
        align: "start",
    },
    {
        id: "bulk-actions",
        target: { selector: TOUR_TARGETS.bulkActions },
        titleKey: "tour.steps.bulkActions.title",
        descriptionKey: "tour.steps.bulkActions.description",
        side: "right",
        align: "start",
    },
    {
        id: "auto-actions",
        target: { selector: TOUR_TARGETS.autoActions },
        titleKey: "tour.steps.autoActions.title",
        descriptionKey: "tour.steps.autoActions.description",
        side: "right",
        align: "start",
    },
    {
        id: "statistics",
        target: { selector: TOUR_TARGETS.statistics },
        titleKey: "tour.steps.statistics.title",
        descriptionKey: "tour.steps.statistics.description",
        side: "left",
        align: "start",
    },
    {
        id: "statistics-pie-chart",
        target: { selector: TOUR_TARGETS.statisticsPieChart },
        titleKey: "tour.steps.statisticsPieChart.title",
        descriptionKey: "tour.steps.statisticsPieChart.description",
        side: "left",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "statistics-histogram",
        target: { selector: TOUR_TARGETS.statisticsHistogram },
        titleKey: "tour.steps.statisticsHistogram.title",
        descriptionKey: "tour.steps.statisticsHistogram.description",
        side: "left",
        align: "start",
        waitForElementMs: 2_000,
    },
    {
        id: "chat",
        target: { selector: TOUR_TARGETS.chat },
        titleKey: "tour.steps.chat.title",
        descriptionKey: "tour.steps.chat.description",
        side: "left",
        align: "start",
    },
    {
        id: "processing-status",
        target: { selector: TOUR_TARGETS.processingStatus },
        titleKey: "tour.steps.processingStatus.title",
        descriptionKey: "tour.steps.processingStatus.description",
        side: "bottom",
        align: "end",
    },
    {
        id: "navigation",
        target: { selector: TOUR_TARGETS.navigation },
        titleKey: "tour.steps.navigation.title",
        descriptionKey: "tour.steps.navigation.description",
        side: "bottom",
        align: "end",
    },
    {
        id: "menu",
        target: { selector: TOUR_TARGETS.menu },
        titleKey: "tour.steps.menu.title",
        descriptionKey: "tour.steps.menu.description",
        side: "bottom",
        align: "end",
        waitForElementMs: 2_000,
    },
    {
        id: "conclusion",
        target: { selector: TOUR_TARGETS.branding },
        titleKey: "tour.steps.conclusion.title",
        descriptionKey: "tour.steps.conclusion.description",
        side: "bottom",
        align: "start",
    },
];
